/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesDomainListResponseDtoPaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
// @ts-ignore
import type { TenantApiTenantV1CreateDomainRequest } from '../models';
// @ts-ignore
import type { TenantApiTenantV1DomainCreatedResponse } from '../models';
// @ts-ignore
import type { TenantApiTenantV1DomainProfileResponse } from '../models';
// @ts-ignore
import type { TenantApiTenantV1DomainUpdatedResponse } from '../models';
// @ts-ignore
import type { TenantApiTenantV1DomainVerifiedResponse } from '../models';
// @ts-ignore
import type { TenantApiTenantV1UpdateDomainRequest } from '../models';
// @ts-ignore
import type { TenantApiTenantV1VerifyDomainRequest } from '../models';
/**
 * DomainsApi - axios parameter creator
 * @export
 */
export const DomainsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new domain
         * @param {string} tenantId 
         * @param {TenantApiTenantV1CreateDomainRequest} [tenantApiTenantV1CreateDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantDomainAsync: async (tenantId: string, tenantApiTenantV1CreateDomainRequest?: TenantApiTenantV1CreateDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createTenantDomainAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/domains`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tenantApiTenantV1CreateDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a user
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantDomainAsync: async (tenantId: string, domainName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteTenantDomainAsync', 'tenantId', tenantId)
            // verify required parameter 'domainName' is not null or undefined
            assertParamExists('deleteTenantDomainAsync', 'domainName', domainName)
            const localVarPath = `/tenants/{tenantId}/domains/{domainName}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"domainName"}}`, encodeURIComponent(String(domainName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of domains associated to this tenant
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantDomainsAsync: async (tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getAllTenantDomainsAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/domains`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantDomainProfileByNameAsync: async (tenantId: string, domainName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getTenantDomainProfileByNameAsync', 'tenantId', tenantId)
            // verify required parameter 'domainName' is not null or undefined
            assertParamExists('getTenantDomainProfileByNameAsync', 'domainName', domainName)
            const localVarPath = `/tenants/{tenantId}/domains/{domainName}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"domainName"}}`, encodeURIComponent(String(domainName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {TenantApiTenantV1UpdateDomainRequest} [tenantApiTenantV1UpdateDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantDomainAsync: async (tenantId: string, domainName: string, tenantApiTenantV1UpdateDomainRequest?: TenantApiTenantV1UpdateDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateTenantDomainAsync', 'tenantId', tenantId)
            // verify required parameter 'domainName' is not null or undefined
            assertParamExists('updateTenantDomainAsync', 'domainName', domainName)
            const localVarPath = `/tenants/{tenantId}/domains/{domainName}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"domainName"}}`, encodeURIComponent(String(domainName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tenantApiTenantV1UpdateDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify a  tenant\'s domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {TenantApiTenantV1VerifyDomainRequest} [tenantApiTenantV1VerifyDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyTenantDomainAsync: async (tenantId: string, domainName: string, tenantApiTenantV1VerifyDomainRequest?: TenantApiTenantV1VerifyDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('verifyTenantDomainAsync', 'tenantId', tenantId)
            // verify required parameter 'domainName' is not null or undefined
            assertParamExists('verifyTenantDomainAsync', 'domainName', domainName)
            const localVarPath = `/tenants/{tenantId}/domains/{domainName}/verify`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"domainName"}}`, encodeURIComponent(String(domainName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tenantApiTenantV1VerifyDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DomainsApi - functional programming interface
 * @export
 */
export const DomainsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DomainsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a new domain
         * @param {string} tenantId 
         * @param {TenantApiTenantV1CreateDomainRequest} [tenantApiTenantV1CreateDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTenantDomainAsync(tenantId: string, tenantApiTenantV1CreateDomainRequest?: TenantApiTenantV1CreateDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1DomainCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTenantDomainAsync(tenantId, tenantApiTenantV1CreateDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.createTenantDomainAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a user
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTenantDomainAsync(tenantId: string, domainName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTenantDomainAsync(tenantId, domainName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.deleteTenantDomainAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of domains associated to this tenant
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTenantDomainsAsync(tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesDomainListResponseDtoPaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTenantDomainsAsync(tenantId, pageSize, pageIndex, orderBy, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.getAllTenantDomainsAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantDomainProfileByNameAsync(tenantId: string, domainName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1DomainProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantDomainProfileByNameAsync(tenantId, domainName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.getTenantDomainProfileByNameAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {TenantApiTenantV1UpdateDomainRequest} [tenantApiTenantV1UpdateDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTenantDomainAsync(tenantId: string, domainName: string, tenantApiTenantV1UpdateDomainRequest?: TenantApiTenantV1UpdateDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1DomainUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTenantDomainAsync(tenantId, domainName, tenantApiTenantV1UpdateDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.updateTenantDomainAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify a  tenant\'s domain
         * @param {string} tenantId 
         * @param {string} domainName 
         * @param {TenantApiTenantV1VerifyDomainRequest} [tenantApiTenantV1VerifyDomainRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyTenantDomainAsync(tenantId: string, domainName: string, tenantApiTenantV1VerifyDomainRequest?: TenantApiTenantV1VerifyDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1DomainVerifiedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyTenantDomainAsync(tenantId, domainName, tenantApiTenantV1VerifyDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.verifyTenantDomainAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DomainsApi - factory interface
 * @export
 */
export const DomainsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DomainsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a new domain
         * @param {DomainsApiCreateTenantDomainAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantDomainAsync(requestParameters: DomainsApiCreateTenantDomainAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1DomainCreatedResponse> {
            return localVarFp.createTenantDomainAsync(requestParameters.tenantId, requestParameters.tenantApiTenantV1CreateDomainRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a user
         * @param {DomainsApiDeleteTenantDomainAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantDomainAsync(requestParameters: DomainsApiDeleteTenantDomainAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of domains associated to this tenant
         * @param {DomainsApiGetAllTenantDomainsAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantDomainsAsync(requestParameters: DomainsApiGetAllTenantDomainsAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesDomainListResponseDtoPaginatedItemsViewModel> {
            return localVarFp.getAllTenantDomainsAsync(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a domain
         * @param {DomainsApiGetTenantDomainProfileByNameAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantDomainProfileByNameAsync(requestParameters: DomainsApiGetTenantDomainProfileByNameAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1DomainProfileResponse> {
            return localVarFp.getTenantDomainProfileByNameAsync(requestParameters.tenantId, requestParameters.domainName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a domain
         * @param {DomainsApiUpdateTenantDomainAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantDomainAsync(requestParameters: DomainsApiUpdateTenantDomainAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1DomainUpdatedResponse> {
            return localVarFp.updateTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, requestParameters.tenantApiTenantV1UpdateDomainRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify a  tenant\'s domain
         * @param {DomainsApiVerifyTenantDomainAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyTenantDomainAsync(requestParameters: DomainsApiVerifyTenantDomainAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1DomainVerifiedResponse> {
            return localVarFp.verifyTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, requestParameters.tenantApiTenantV1VerifyDomainRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTenantDomainAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiCreateTenantDomainAsyncRequest
 */
export interface DomainsApiCreateTenantDomainAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiCreateTenantDomainAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {TenantApiTenantV1CreateDomainRequest}
     * @memberof DomainsApiCreateTenantDomainAsync
     */
    readonly tenantApiTenantV1CreateDomainRequest?: TenantApiTenantV1CreateDomainRequest
}

/**
 * Request parameters for deleteTenantDomainAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiDeleteTenantDomainAsyncRequest
 */
export interface DomainsApiDeleteTenantDomainAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiDeleteTenantDomainAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof DomainsApiDeleteTenantDomainAsync
     */
    readonly domainName: string
}

/**
 * Request parameters for getAllTenantDomainsAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiGetAllTenantDomainsAsyncRequest
 */
export interface DomainsApiGetAllTenantDomainsAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiGetAllTenantDomainsAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof DomainsApiGetAllTenantDomainsAsync
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof DomainsApiGetAllTenantDomainsAsync
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {string}
     * @memberof DomainsApiGetAllTenantDomainsAsync
     */
    readonly orderBy?: string

    /**
     * 
     * @type {string}
     * @memberof DomainsApiGetAllTenantDomainsAsync
     */
    readonly filter?: string
}

/**
 * Request parameters for getTenantDomainProfileByNameAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiGetTenantDomainProfileByNameAsyncRequest
 */
export interface DomainsApiGetTenantDomainProfileByNameAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiGetTenantDomainProfileByNameAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof DomainsApiGetTenantDomainProfileByNameAsync
     */
    readonly domainName: string
}

/**
 * Request parameters for updateTenantDomainAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiUpdateTenantDomainAsyncRequest
 */
export interface DomainsApiUpdateTenantDomainAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiUpdateTenantDomainAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof DomainsApiUpdateTenantDomainAsync
     */
    readonly domainName: string

    /**
     * 
     * @type {TenantApiTenantV1UpdateDomainRequest}
     * @memberof DomainsApiUpdateTenantDomainAsync
     */
    readonly tenantApiTenantV1UpdateDomainRequest?: TenantApiTenantV1UpdateDomainRequest
}

/**
 * Request parameters for verifyTenantDomainAsync operation in DomainsApi.
 * @export
 * @interface DomainsApiVerifyTenantDomainAsyncRequest
 */
export interface DomainsApiVerifyTenantDomainAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainsApiVerifyTenantDomainAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof DomainsApiVerifyTenantDomainAsync
     */
    readonly domainName: string

    /**
     * 
     * @type {TenantApiTenantV1VerifyDomainRequest}
     * @memberof DomainsApiVerifyTenantDomainAsync
     */
    readonly tenantApiTenantV1VerifyDomainRequest?: TenantApiTenantV1VerifyDomainRequest
}

/**
 * DomainsApi - object-oriented interface
 * @export
 * @class DomainsApi
 * @extends {BaseAPI}
 */
export class DomainsApi extends BaseAPI {
    /**
     * 
     * @summary Creates a new domain
     * @param {DomainsApiCreateTenantDomainAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public createTenantDomainAsync(requestParameters: DomainsApiCreateTenantDomainAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).createTenantDomainAsync(requestParameters.tenantId, requestParameters.tenantApiTenantV1CreateDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a user
     * @param {DomainsApiDeleteTenantDomainAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public deleteTenantDomainAsync(requestParameters: DomainsApiDeleteTenantDomainAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).deleteTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of domains associated to this tenant
     * @param {DomainsApiGetAllTenantDomainsAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public getAllTenantDomainsAsync(requestParameters: DomainsApiGetAllTenantDomainsAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).getAllTenantDomainsAsync(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a domain
     * @param {DomainsApiGetTenantDomainProfileByNameAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public getTenantDomainProfileByNameAsync(requestParameters: DomainsApiGetTenantDomainProfileByNameAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).getTenantDomainProfileByNameAsync(requestParameters.tenantId, requestParameters.domainName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a domain
     * @param {DomainsApiUpdateTenantDomainAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public updateTenantDomainAsync(requestParameters: DomainsApiUpdateTenantDomainAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).updateTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, requestParameters.tenantApiTenantV1UpdateDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify a  tenant\'s domain
     * @param {DomainsApiVerifyTenantDomainAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApi
     */
    public verifyTenantDomainAsync(requestParameters: DomainsApiVerifyTenantDomainAsyncRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).verifyTenantDomainAsync(requestParameters.tenantId, requestParameters.domainName, requestParameters.tenantApiTenantV1VerifyDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

