/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AnalyticsApiGroupsV1AddGroupUsersRequest } from '../models';
// @ts-ignore
import type { AnalyticsApiGroupsV1CreateGroupRequest } from '../models';
// @ts-ignore
import type { AnalyticsApiGroupsV1GroupResponse } from '../models';
// @ts-ignore
import type { AnalyticsApiGroupsV1GroupUsersResponse } from '../models';
// @ts-ignore
import type { AnalyticsApiGroupsV1GroupsResponse } from '../models';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcProblemDetails } from '../models';
/**
 * GroupsApi - axios parameter creator
 * @export
 */
export const GroupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Adds users to group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {AnalyticsApiGroupsV1AddGroupUsersRequest} [analyticsApiGroupsV1AddGroupUsersRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUsersToGroupAsync: async (tenantId: string, groupId: string, analyticsApiGroupsV1AddGroupUsersRequest?: AnalyticsApiGroupsV1AddGroupUsersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('addUsersToGroupAsync', 'tenantId', tenantId)
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('addUsersToGroupAsync', 'groupId', groupId)
            const localVarPath = `/tenants/{tenantId}/analytics/groups/{groupId}/users/bulk`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(analyticsApiGroupsV1AddGroupUsersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a group.
         * @param {string} tenantId 
         * @param {AnalyticsApiGroupsV1CreateGroupRequest} [analyticsApiGroupsV1CreateGroupRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAnalyticsPowerBiGroup: async (tenantId: string, analyticsApiGroupsV1CreateGroupRequest?: AnalyticsApiGroupsV1CreateGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createAnalyticsPowerBiGroup', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/analytics/groups`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(analyticsApiGroupsV1CreateGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAnalyticsPowerBiGroup: async (tenantId: string, groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteAnalyticsPowerBiGroup', 'tenantId', tenantId)
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('deleteAnalyticsPowerBiGroup', 'groupId', groupId)
            const localVarPath = `/tenants/{tenantId}/analytics/groups/{groupId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves all users for a specific group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {number} [skipFirstN] 
         * @param {number} [topFirstN] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalyticsPowerBiGroupUsers: async (tenantId: string, groupId: string, skipFirstN?: number, topFirstN?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getAnalyticsPowerBiGroupUsers', 'tenantId', tenantId)
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getAnalyticsPowerBiGroupUsers', 'groupId', groupId)
            const localVarPath = `/tenants/{tenantId}/analytics/groups/{groupId}/users`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (skipFirstN !== undefined) {
                localVarQueryParameter['skipFirstN'] = skipFirstN;
            }

            if (topFirstN !== undefined) {
                localVarQueryParameter['topFirstN'] = topFirstN;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of groups.
         * @param {string} tenantId 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupsAsync: async (tenantId: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getGroupsAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/analytics/groups`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupsApi - functional programming interface
 * @export
 */
export const GroupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Adds users to group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {AnalyticsApiGroupsV1AddGroupUsersRequest} [analyticsApiGroupsV1AddGroupUsersRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addUsersToGroupAsync(tenantId: string, groupId: string, analyticsApiGroupsV1AddGroupUsersRequest?: AnalyticsApiGroupsV1AddGroupUsersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addUsersToGroupAsync(tenantId, groupId, analyticsApiGroupsV1AddGroupUsersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.addUsersToGroupAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a group.
         * @param {string} tenantId 
         * @param {AnalyticsApiGroupsV1CreateGroupRequest} [analyticsApiGroupsV1CreateGroupRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAnalyticsPowerBiGroup(tenantId: string, analyticsApiGroupsV1CreateGroupRequest?: AnalyticsApiGroupsV1CreateGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnalyticsApiGroupsV1GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAnalyticsPowerBiGroup(tenantId, analyticsApiGroupsV1CreateGroupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.createAnalyticsPowerBiGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAnalyticsPowerBiGroup(tenantId: string, groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAnalyticsPowerBiGroup(tenantId, groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.deleteAnalyticsPowerBiGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves all users for a specific group.
         * @param {string} tenantId 
         * @param {string} groupId 
         * @param {number} [skipFirstN] 
         * @param {number} [topFirstN] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAnalyticsPowerBiGroupUsers(tenantId: string, groupId: string, skipFirstN?: number, topFirstN?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnalyticsApiGroupsV1GroupUsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAnalyticsPowerBiGroupUsers(tenantId, groupId, skipFirstN, topFirstN, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.getAnalyticsPowerBiGroupUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of groups.
         * @param {string} tenantId 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupsAsync(tenantId: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnalyticsApiGroupsV1GroupsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroupsAsync(tenantId, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.getGroupsAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupsApi - factory interface
 * @export
 */
export const GroupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupsApiFp(configuration)
    return {
        /**
         * 
         * @summary Adds users to group.
         * @param {GroupsApiAddUsersToGroupAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUsersToGroupAsync(requestParameters: GroupsApiAddUsersToGroupAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addUsersToGroupAsync(requestParameters.tenantId, requestParameters.groupId, requestParameters.analyticsApiGroupsV1AddGroupUsersRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a group.
         * @param {GroupsApiCreateAnalyticsPowerBiGroupRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAnalyticsPowerBiGroup(requestParameters: GroupsApiCreateAnalyticsPowerBiGroupRequest, options?: RawAxiosRequestConfig): AxiosPromise<AnalyticsApiGroupsV1GroupResponse> {
            return localVarFp.createAnalyticsPowerBiGroup(requestParameters.tenantId, requestParameters.analyticsApiGroupsV1CreateGroupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a group.
         * @param {GroupsApiDeleteAnalyticsPowerBiGroupRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAnalyticsPowerBiGroup(requestParameters: GroupsApiDeleteAnalyticsPowerBiGroupRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAnalyticsPowerBiGroup(requestParameters.tenantId, requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves all users for a specific group.
         * @param {GroupsApiGetAnalyticsPowerBiGroupUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalyticsPowerBiGroupUsers(requestParameters: GroupsApiGetAnalyticsPowerBiGroupUsersRequest, options?: RawAxiosRequestConfig): AxiosPromise<AnalyticsApiGroupsV1GroupUsersResponse> {
            return localVarFp.getAnalyticsPowerBiGroupUsers(requestParameters.tenantId, requestParameters.groupId, requestParameters.skipFirstN, requestParameters.topFirstN, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of groups.
         * @param {GroupsApiGetGroupsAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupsAsync(requestParameters: GroupsApiGetGroupsAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<AnalyticsApiGroupsV1GroupsResponse> {
            return localVarFp.getGroupsAsync(requestParameters.tenantId, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addUsersToGroupAsync operation in GroupsApi.
 * @export
 * @interface GroupsApiAddUsersToGroupAsyncRequest
 */
export interface GroupsApiAddUsersToGroupAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsApiAddUsersToGroupAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof GroupsApiAddUsersToGroupAsync
     */
    readonly groupId: string

    /**
     * 
     * @type {AnalyticsApiGroupsV1AddGroupUsersRequest}
     * @memberof GroupsApiAddUsersToGroupAsync
     */
    readonly analyticsApiGroupsV1AddGroupUsersRequest?: AnalyticsApiGroupsV1AddGroupUsersRequest
}

/**
 * Request parameters for createAnalyticsPowerBiGroup operation in GroupsApi.
 * @export
 * @interface GroupsApiCreateAnalyticsPowerBiGroupRequest
 */
export interface GroupsApiCreateAnalyticsPowerBiGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsApiCreateAnalyticsPowerBiGroup
     */
    readonly tenantId: string

    /**
     * 
     * @type {AnalyticsApiGroupsV1CreateGroupRequest}
     * @memberof GroupsApiCreateAnalyticsPowerBiGroup
     */
    readonly analyticsApiGroupsV1CreateGroupRequest?: AnalyticsApiGroupsV1CreateGroupRequest
}

/**
 * Request parameters for deleteAnalyticsPowerBiGroup operation in GroupsApi.
 * @export
 * @interface GroupsApiDeleteAnalyticsPowerBiGroupRequest
 */
export interface GroupsApiDeleteAnalyticsPowerBiGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsApiDeleteAnalyticsPowerBiGroup
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof GroupsApiDeleteAnalyticsPowerBiGroup
     */
    readonly groupId: string
}

/**
 * Request parameters for getAnalyticsPowerBiGroupUsers operation in GroupsApi.
 * @export
 * @interface GroupsApiGetAnalyticsPowerBiGroupUsersRequest
 */
export interface GroupsApiGetAnalyticsPowerBiGroupUsersRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsApiGetAnalyticsPowerBiGroupUsers
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof GroupsApiGetAnalyticsPowerBiGroupUsers
     */
    readonly groupId: string

    /**
     * 
     * @type {number}
     * @memberof GroupsApiGetAnalyticsPowerBiGroupUsers
     */
    readonly skipFirstN?: number

    /**
     * 
     * @type {number}
     * @memberof GroupsApiGetAnalyticsPowerBiGroupUsers
     */
    readonly topFirstN?: number
}

/**
 * Request parameters for getGroupsAsync operation in GroupsApi.
 * @export
 * @interface GroupsApiGetGroupsAsyncRequest
 */
export interface GroupsApiGetGroupsAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsApiGetGroupsAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof GroupsApiGetGroupsAsync
     */
    readonly filter?: string
}

/**
 * GroupsApi - object-oriented interface
 * @export
 * @class GroupsApi
 * @extends {BaseAPI}
 */
export class GroupsApi extends BaseAPI {
    /**
     * 
     * @summary Adds users to group.
     * @param {GroupsApiAddUsersToGroupAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public addUsersToGroupAsync(requestParameters: GroupsApiAddUsersToGroupAsyncRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).addUsersToGroupAsync(requestParameters.tenantId, requestParameters.groupId, requestParameters.analyticsApiGroupsV1AddGroupUsersRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a group.
     * @param {GroupsApiCreateAnalyticsPowerBiGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public createAnalyticsPowerBiGroup(requestParameters: GroupsApiCreateAnalyticsPowerBiGroupRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).createAnalyticsPowerBiGroup(requestParameters.tenantId, requestParameters.analyticsApiGroupsV1CreateGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a group.
     * @param {GroupsApiDeleteAnalyticsPowerBiGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public deleteAnalyticsPowerBiGroup(requestParameters: GroupsApiDeleteAnalyticsPowerBiGroupRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).deleteAnalyticsPowerBiGroup(requestParameters.tenantId, requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves all users for a specific group.
     * @param {GroupsApiGetAnalyticsPowerBiGroupUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public getAnalyticsPowerBiGroupUsers(requestParameters: GroupsApiGetAnalyticsPowerBiGroupUsersRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).getAnalyticsPowerBiGroupUsers(requestParameters.tenantId, requestParameters.groupId, requestParameters.skipFirstN, requestParameters.topFirstN, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of groups.
     * @param {GroupsApiGetGroupsAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public getGroupsAsync(requestParameters: GroupsApiGetGroupsAsyncRequest, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).getGroupsAsync(requestParameters.tenantId, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }
}

