/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest } from '../models';
// @ts-ignore
import type { IdentityApiInvitationV1InvitationListResponsePaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { IdentityApiInvitationV1InvitationResponse } from '../models';
// @ts-ignore
import type { IdentityApiInvitationV1InvitationSentResponse } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * InvitationsApi - axios parameter creator
 * @export
 */
export const InvitationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes an invitation
         * @param {string} tenantId 
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantInvitationAsync: async (tenantId: string, invitationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteTenantInvitationAsync', 'tenantId', tenantId)
            // verify required parameter 'invitationId' is not null or undefined
            assertParamExists('deleteTenantInvitationAsync', 'invitationId', invitationId)
            const localVarPath = `/tenants/{tenantId}/invitations/{invitationId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"invitationId"}}`, encodeURIComponent(String(invitationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of invitations associated to this tenant
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantInvitationsAsync: async (tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getAllTenantInvitationsAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/invitations`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a specific invitation
         * @param {string} tenantId 
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantInvitationByIdAsync: async (tenantId: string, invitationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getTenantInvitationByIdAsync', 'tenantId', tenantId)
            // verify required parameter 'invitationId' is not null or undefined
            assertParamExists('getTenantInvitationByIdAsync', 'invitationId', invitationId)
            const localVarPath = `/tenants/{tenantId}/invitations/{invitationId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"invitationId"}}`, encodeURIComponent(String(invitationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates and sends an invitation to a user
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTenantInvitationAsync: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('sendTenantInvitationAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/invitations`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvitationsApi - functional programming interface
 * @export
 */
export const InvitationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvitationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deletes an invitation
         * @param {string} tenantId 
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTenantInvitationAsync(tenantId: string, invitationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTenantInvitationAsync(tenantId, invitationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitationsApi.deleteTenantInvitationAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of invitations associated to this tenant
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTenantInvitationsAsync(tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdentityApiInvitationV1InvitationListResponsePaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTenantInvitationsAsync(tenantId, pageSize, pageIndex, orderBy, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitationsApi.getAllTenantInvitationsAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a specific invitation
         * @param {string} tenantId 
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantInvitationByIdAsync(tenantId: string, invitationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdentityApiInvitationV1InvitationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantInvitationByIdAsync(tenantId, invitationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitationsApi.getTenantInvitationByIdAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates and sends an invitation to a user
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendTenantInvitationAsync(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdentityApiInvitationV1InvitationSentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendTenantInvitationAsync(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvitationsApi.sendTenantInvitationAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvitationsApi - factory interface
 * @export
 */
export const InvitationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvitationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Deletes an invitation
         * @param {InvitationsApiDeleteTenantInvitationAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantInvitationAsync(requestParameters: InvitationsApiDeleteTenantInvitationAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTenantInvitationAsync(requestParameters.tenantId, requestParameters.invitationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of invitations associated to this tenant
         * @param {InvitationsApiGetAllTenantInvitationsAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantInvitationsAsync(requestParameters: InvitationsApiGetAllTenantInvitationsAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<IdentityApiInvitationV1InvitationListResponsePaginatedItemsViewModel> {
            return localVarFp.getAllTenantInvitationsAsync(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a specific invitation
         * @param {InvitationsApiGetTenantInvitationByIdAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantInvitationByIdAsync(requestParameters: InvitationsApiGetTenantInvitationByIdAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<IdentityApiInvitationV1InvitationResponse> {
            return localVarFp.getTenantInvitationByIdAsync(requestParameters.tenantId, requestParameters.invitationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates and sends an invitation to a user
         * @param {InvitationsApiSendTenantInvitationAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTenantInvitationAsync(requestParameters: InvitationsApiSendTenantInvitationAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<IdentityApiInvitationV1InvitationSentResponse> {
            return localVarFp.sendTenantInvitationAsync(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteTenantInvitationAsync operation in InvitationsApi.
 * @export
 * @interface InvitationsApiDeleteTenantInvitationAsyncRequest
 */
export interface InvitationsApiDeleteTenantInvitationAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitationsApiDeleteTenantInvitationAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof InvitationsApiDeleteTenantInvitationAsync
     */
    readonly invitationId: string
}

/**
 * Request parameters for getAllTenantInvitationsAsync operation in InvitationsApi.
 * @export
 * @interface InvitationsApiGetAllTenantInvitationsAsyncRequest
 */
export interface InvitationsApiGetAllTenantInvitationsAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitationsApiGetAllTenantInvitationsAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof InvitationsApiGetAllTenantInvitationsAsync
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof InvitationsApiGetAllTenantInvitationsAsync
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {string}
     * @memberof InvitationsApiGetAllTenantInvitationsAsync
     */
    readonly orderBy?: string

    /**
     * 
     * @type {string}
     * @memberof InvitationsApiGetAllTenantInvitationsAsync
     */
    readonly filter?: string
}

/**
 * Request parameters for getTenantInvitationByIdAsync operation in InvitationsApi.
 * @export
 * @interface InvitationsApiGetTenantInvitationByIdAsyncRequest
 */
export interface InvitationsApiGetTenantInvitationByIdAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitationsApiGetTenantInvitationByIdAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof InvitationsApiGetTenantInvitationByIdAsync
     */
    readonly invitationId: string
}

/**
 * Request parameters for sendTenantInvitationAsync operation in InvitationsApi.
 * @export
 * @interface InvitationsApiSendTenantInvitationAsyncRequest
 */
export interface InvitationsApiSendTenantInvitationAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitationsApiSendTenantInvitationAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest}
     * @memberof InvitationsApiSendTenantInvitationAsync
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest
}

/**
 * InvitationsApi - object-oriented interface
 * @export
 * @class InvitationsApi
 * @extends {BaseAPI}
 */
export class InvitationsApi extends BaseAPI {
    /**
     * 
     * @summary Deletes an invitation
     * @param {InvitationsApiDeleteTenantInvitationAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public deleteTenantInvitationAsync(requestParameters: InvitationsApiDeleteTenantInvitationAsyncRequest, options?: RawAxiosRequestConfig) {
        return InvitationsApiFp(this.configuration).deleteTenantInvitationAsync(requestParameters.tenantId, requestParameters.invitationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of invitations associated to this tenant
     * @param {InvitationsApiGetAllTenantInvitationsAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public getAllTenantInvitationsAsync(requestParameters: InvitationsApiGetAllTenantInvitationsAsyncRequest, options?: RawAxiosRequestConfig) {
        return InvitationsApiFp(this.configuration).getAllTenantInvitationsAsync(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a specific invitation
     * @param {InvitationsApiGetTenantInvitationByIdAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public getTenantInvitationByIdAsync(requestParameters: InvitationsApiGetTenantInvitationByIdAsyncRequest, options?: RawAxiosRequestConfig) {
        return InvitationsApiFp(this.configuration).getTenantInvitationByIdAsync(requestParameters.tenantId, requestParameters.invitationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates and sends an invitation to a user
     * @param {InvitationsApiSendTenantInvitationAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public sendTenantInvitationAsync(requestParameters: InvitationsApiSendTenantInvitationAsyncRequest, options?: RawAxiosRequestConfig) {
        return InvitationsApiFp(this.configuration).sendTenantInvitationAsync(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

