/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DataSyncApiJobV1ActivateJobRequest } from '../models';
// @ts-ignore
import type { DataSyncApiJobV1CancelJobRequest } from '../models';
// @ts-ignore
import type { DataSyncApiJobV1DeactivateJobRequest } from '../models';
// @ts-ignore
import type { DataSyncApiJobV1ExecuteJobRequest } from '../models';
// @ts-ignore
import type { DataSyncApiJobV1JobListResponsePaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { DataSyncApiJobV1JobProfileResponse } from '../models';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcProblemDetails } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
// @ts-ignore
import type { ValidationsApiCoreV1CreatedResponse } from '../models';
// @ts-ignore
import type { ValidationsApiJobsV1JobProfileResponse } from '../models';
// @ts-ignore
import type { ValidationsApiJobsV1PaginatedItemsResponse } from '../models';
/**
 * JobsApi - axios parameter creator
 * @export
 */
export const JobsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Activate a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1ActivateJobRequest} [dataSyncApiJobV1ActivateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateTenantDataSyncJob: async (tenantId: string, jobId: string, dataSyncApiJobV1ActivateJobRequest?: DataSyncApiJobV1ActivateJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('activateTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('activateTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}/activate`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataSyncApiJobV1ActivateJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Requests a Job cancellation.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelJob: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('cancelJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('cancelJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}/cancel`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1CancelJobRequest} [dataSyncApiJobV1CancelJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTenantDataSyncJob: async (tenantId: string, jobId: string, dataSyncApiJobV1CancelJobRequest?: DataSyncApiJobV1CancelJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('cancelTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('cancelTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}/cancel`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataSyncApiJobV1CancelJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a Job.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJob: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createJob', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new DataSync job
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantDataSyncJob: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createTenantDataSyncJob', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deactivate a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1DeactivateJobRequest} [dataSyncApiJobV1DeactivateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateTenantDataSyncJob: async (tenantId: string, jobId: string, dataSyncApiJobV1DeactivateJobRequest?: DataSyncApiJobV1DeactivateJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deactivateTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('deactivateTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}/deactivate`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataSyncApiJobV1DeactivateJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a Job.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJob: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('deleteJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantDataSyncJob: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('deleteTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Requests a Job execution.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeJob: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('executeJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('executeJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}/execute`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Execute a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1ExecuteJobRequest} [dataSyncApiJobV1ExecuteJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeTenantDataSyncJob: async (tenantId: string, jobId: string, dataSyncApiJobV1ExecuteJobRequest?: DataSyncApiJobV1ExecuteJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('executeTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('executeTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}/execute`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataSyncApiJobV1ExecuteJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of DataSync Jobs
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantDataSyncJobs: async (tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getAllTenantDataSyncJobs', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a Job by ID.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobById: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getJobById', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getJobById', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of Jobs.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobs: async (tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getJobs', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a specific DataSync job using its primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantDataSyncJobProfileById: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getTenantDataSyncJobProfileById', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getTenantDataSyncJobProfileById', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Requests a Job schedule restart.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartJobSchedule: async (tenantId: string, jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('restartJobSchedule', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('restartJobSchedule', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}/restart`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a Job.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateJob: async (tenantId: string, jobId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('updateJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/validations/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantDataSyncJob: async (tenantId: string, jobId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateTenantDataSyncJob', 'tenantId', tenantId)
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('updateTenantDataSyncJob', 'jobId', jobId)
            const localVarPath = `/tenants/{tenantId}/datasync/jobs/{jobId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobsApi - functional programming interface
 * @export
 */
export const JobsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JobsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Activate a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1ActivateJobRequest} [dataSyncApiJobV1ActivateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activateTenantDataSyncJob(tenantId: string, jobId: string, dataSyncApiJobV1ActivateJobRequest?: DataSyncApiJobV1ActivateJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activateTenantDataSyncJob(tenantId, jobId, dataSyncApiJobV1ActivateJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.activateTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Requests a Job cancellation.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelJob(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelJob(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.cancelJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cancel a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1CancelJobRequest} [dataSyncApiJobV1CancelJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelTenantDataSyncJob(tenantId: string, jobId: string, dataSyncApiJobV1CancelJobRequest?: DataSyncApiJobV1CancelJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelTenantDataSyncJob(tenantId, jobId, dataSyncApiJobV1CancelJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.cancelTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a Job.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJob(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ValidationsApiCoreV1CreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJob(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.createJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a new DataSync job
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTenantDataSyncJob(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTenantDataSyncJob(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.createTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deactivate a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1DeactivateJobRequest} [dataSyncApiJobV1DeactivateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivateTenantDataSyncJob(tenantId: string, jobId: string, dataSyncApiJobV1DeactivateJobRequest?: DataSyncApiJobV1DeactivateJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivateTenantDataSyncJob(tenantId, jobId, dataSyncApiJobV1DeactivateJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.deactivateTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a Job.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteJob(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteJob(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.deleteJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTenantDataSyncJob(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTenantDataSyncJob(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.deleteTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Requests a Job execution.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async executeJob(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.executeJob(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.executeJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Execute a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {DataSyncApiJobV1ExecuteJobRequest} [dataSyncApiJobV1ExecuteJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async executeTenantDataSyncJob(tenantId: string, jobId: string, dataSyncApiJobV1ExecuteJobRequest?: DataSyncApiJobV1ExecuteJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.executeTenantDataSyncJob(tenantId, jobId, dataSyncApiJobV1ExecuteJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.executeTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of DataSync Jobs
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTenantDataSyncJobs(tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DataSyncApiJobV1JobListResponsePaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTenantDataSyncJobs(tenantId, pageSize, pageIndex, orderBy, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.getAllTenantDataSyncJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a Job by ID.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobById(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ValidationsApiJobsV1JobProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobById(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.getJobById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of Jobs.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobs(tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ValidationsApiJobsV1PaginatedItemsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobs(tenantId, pageIndex, pageSize, filter, orderBy, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.getJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a specific DataSync job using its primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantDataSyncJobProfileById(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DataSyncApiJobV1JobProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantDataSyncJobProfileById(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.getTenantDataSyncJobProfileById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Requests a Job schedule restart.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restartJobSchedule(tenantId: string, jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restartJobSchedule(tenantId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.restartJobSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a Job.
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateJob(tenantId: string, jobId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateJob(tenantId, jobId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.updateJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a DataSync job matching the primary key
         * @param {string} tenantId 
         * @param {string} jobId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTenantDataSyncJob(tenantId: string, jobId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTenantDataSyncJob(tenantId, jobId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.updateTenantDataSyncJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JobsApi - factory interface
 * @export
 */
export const JobsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JobsApiFp(configuration)
    return {
        /**
         * 
         * @summary Activate a DataSync job matching the primary key
         * @param {JobsApiActivateTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateTenantDataSyncJob(requestParameters: JobsApiActivateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.activateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1ActivateJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Requests a Job cancellation.
         * @param {JobsApiCancelJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelJob(requestParameters: JobsApiCancelJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.cancelJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel a DataSync job matching the primary key
         * @param {JobsApiCancelTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTenantDataSyncJob(requestParameters: JobsApiCancelTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cancelTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1CancelJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a Job.
         * @param {JobsApiCreateJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJob(requestParameters: JobsApiCreateJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<ValidationsApiCoreV1CreatedResponse> {
            return localVarFp.createJob(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new DataSync job
         * @param {JobsApiCreateTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantDataSyncJob(requestParameters: JobsApiCreateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTenantDataSyncJob(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deactivate a DataSync job matching the primary key
         * @param {JobsApiDeactivateTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateTenantDataSyncJob(requestParameters: JobsApiDeactivateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deactivateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1DeactivateJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a Job.
         * @param {JobsApiDeleteJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJob(requestParameters: JobsApiDeleteJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a DataSync job matching the primary key
         * @param {JobsApiDeleteTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenantDataSyncJob(requestParameters: JobsApiDeleteTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Requests a Job execution.
         * @param {JobsApiExecuteJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeJob(requestParameters: JobsApiExecuteJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.executeJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Execute a DataSync job matching the primary key
         * @param {JobsApiExecuteTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeTenantDataSyncJob(requestParameters: JobsApiExecuteTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.executeTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1ExecuteJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of DataSync Jobs
         * @param {JobsApiGetAllTenantDataSyncJobsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTenantDataSyncJobs(requestParameters: JobsApiGetAllTenantDataSyncJobsRequest, options?: RawAxiosRequestConfig): AxiosPromise<DataSyncApiJobV1JobListResponsePaginatedItemsViewModel> {
            return localVarFp.getAllTenantDataSyncJobs(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a Job by ID.
         * @param {JobsApiGetJobByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobById(requestParameters: JobsApiGetJobByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ValidationsApiJobsV1JobProfileResponse> {
            return localVarFp.getJobById(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of Jobs.
         * @param {JobsApiGetJobsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobs(requestParameters: JobsApiGetJobsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ValidationsApiJobsV1PaginatedItemsResponse> {
            return localVarFp.getJobs(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a specific DataSync job using its primary key
         * @param {JobsApiGetTenantDataSyncJobProfileByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantDataSyncJobProfileById(requestParameters: JobsApiGetTenantDataSyncJobProfileByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<DataSyncApiJobV1JobProfileResponse> {
            return localVarFp.getTenantDataSyncJobProfileById(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Requests a Job schedule restart.
         * @param {JobsApiRestartJobScheduleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartJobSchedule(requestParameters: JobsApiRestartJobScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.restartJobSchedule(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a Job.
         * @param {JobsApiUpdateJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateJob(requestParameters: JobsApiUpdateJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a DataSync job matching the primary key
         * @param {JobsApiUpdateTenantDataSyncJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantDataSyncJob(requestParameters: JobsApiUpdateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for activateTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiActivateTenantDataSyncJobRequest
 */
export interface JobsApiActivateTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiActivateTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiActivateTenantDataSyncJob
     */
    readonly jobId: string

    /**
     * 
     * @type {DataSyncApiJobV1ActivateJobRequest}
     * @memberof JobsApiActivateTenantDataSyncJob
     */
    readonly dataSyncApiJobV1ActivateJobRequest?: DataSyncApiJobV1ActivateJobRequest
}

/**
 * Request parameters for cancelJob operation in JobsApi.
 * @export
 * @interface JobsApiCancelJobRequest
 */
export interface JobsApiCancelJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiCancelJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiCancelJob
     */
    readonly jobId: string
}

/**
 * Request parameters for cancelTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiCancelTenantDataSyncJobRequest
 */
export interface JobsApiCancelTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiCancelTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiCancelTenantDataSyncJob
     */
    readonly jobId: string

    /**
     * 
     * @type {DataSyncApiJobV1CancelJobRequest}
     * @memberof JobsApiCancelTenantDataSyncJob
     */
    readonly dataSyncApiJobV1CancelJobRequest?: DataSyncApiJobV1CancelJobRequest
}

/**
 * Request parameters for createJob operation in JobsApi.
 * @export
 * @interface JobsApiCreateJobRequest
 */
export interface JobsApiCreateJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiCreateJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest}
     * @memberof JobsApiCreateJob
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest
}

/**
 * Request parameters for createTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiCreateTenantDataSyncJobRequest
 */
export interface JobsApiCreateTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiCreateTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest}
     * @memberof JobsApiCreateTenantDataSyncJob
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest
}

/**
 * Request parameters for deactivateTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiDeactivateTenantDataSyncJobRequest
 */
export interface JobsApiDeactivateTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiDeactivateTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiDeactivateTenantDataSyncJob
     */
    readonly jobId: string

    /**
     * 
     * @type {DataSyncApiJobV1DeactivateJobRequest}
     * @memberof JobsApiDeactivateTenantDataSyncJob
     */
    readonly dataSyncApiJobV1DeactivateJobRequest?: DataSyncApiJobV1DeactivateJobRequest
}

/**
 * Request parameters for deleteJob operation in JobsApi.
 * @export
 * @interface JobsApiDeleteJobRequest
 */
export interface JobsApiDeleteJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiDeleteJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiDeleteJob
     */
    readonly jobId: string
}

/**
 * Request parameters for deleteTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiDeleteTenantDataSyncJobRequest
 */
export interface JobsApiDeleteTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiDeleteTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiDeleteTenantDataSyncJob
     */
    readonly jobId: string
}

/**
 * Request parameters for executeJob operation in JobsApi.
 * @export
 * @interface JobsApiExecuteJobRequest
 */
export interface JobsApiExecuteJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiExecuteJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiExecuteJob
     */
    readonly jobId: string
}

/**
 * Request parameters for executeTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiExecuteTenantDataSyncJobRequest
 */
export interface JobsApiExecuteTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiExecuteTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiExecuteTenantDataSyncJob
     */
    readonly jobId: string

    /**
     * 
     * @type {DataSyncApiJobV1ExecuteJobRequest}
     * @memberof JobsApiExecuteTenantDataSyncJob
     */
    readonly dataSyncApiJobV1ExecuteJobRequest?: DataSyncApiJobV1ExecuteJobRequest
}

/**
 * Request parameters for getAllTenantDataSyncJobs operation in JobsApi.
 * @export
 * @interface JobsApiGetAllTenantDataSyncJobsRequest
 */
export interface JobsApiGetAllTenantDataSyncJobsRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiGetAllTenantDataSyncJobs
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof JobsApiGetAllTenantDataSyncJobs
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof JobsApiGetAllTenantDataSyncJobs
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetAllTenantDataSyncJobs
     */
    readonly orderBy?: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetAllTenantDataSyncJobs
     */
    readonly filter?: string
}

/**
 * Request parameters for getJobById operation in JobsApi.
 * @export
 * @interface JobsApiGetJobByIdRequest
 */
export interface JobsApiGetJobByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiGetJobById
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetJobById
     */
    readonly jobId: string
}

/**
 * Request parameters for getJobs operation in JobsApi.
 * @export
 * @interface JobsApiGetJobsRequest
 */
export interface JobsApiGetJobsRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiGetJobs
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof JobsApiGetJobs
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {number}
     * @memberof JobsApiGetJobs
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetJobs
     */
    readonly filter?: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetJobs
     */
    readonly orderBy?: string
}

/**
 * Request parameters for getTenantDataSyncJobProfileById operation in JobsApi.
 * @export
 * @interface JobsApiGetTenantDataSyncJobProfileByIdRequest
 */
export interface JobsApiGetTenantDataSyncJobProfileByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiGetTenantDataSyncJobProfileById
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiGetTenantDataSyncJobProfileById
     */
    readonly jobId: string
}

/**
 * Request parameters for restartJobSchedule operation in JobsApi.
 * @export
 * @interface JobsApiRestartJobScheduleRequest
 */
export interface JobsApiRestartJobScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiRestartJobSchedule
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiRestartJobSchedule
     */
    readonly jobId: string
}

/**
 * Request parameters for updateJob operation in JobsApi.
 * @export
 * @interface JobsApiUpdateJobRequest
 */
export interface JobsApiUpdateJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiUpdateJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiUpdateJob
     */
    readonly jobId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest}
     * @memberof JobsApiUpdateJob
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest
}

/**
 * Request parameters for updateTenantDataSyncJob operation in JobsApi.
 * @export
 * @interface JobsApiUpdateTenantDataSyncJobRequest
 */
export interface JobsApiUpdateTenantDataSyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobsApiUpdateTenantDataSyncJob
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof JobsApiUpdateTenantDataSyncJob
     */
    readonly jobId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest}
     * @memberof JobsApiUpdateTenantDataSyncJob
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest
}

/**
 * JobsApi - object-oriented interface
 * @export
 * @class JobsApi
 * @extends {BaseAPI}
 */
export class JobsApi extends BaseAPI {
    /**
     * 
     * @summary Activate a DataSync job matching the primary key
     * @param {JobsApiActivateTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public activateTenantDataSyncJob(requestParameters: JobsApiActivateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).activateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1ActivateJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Requests a Job cancellation.
     * @param {JobsApiCancelJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public cancelJob(requestParameters: JobsApiCancelJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).cancelJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel a DataSync job matching the primary key
     * @param {JobsApiCancelTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public cancelTenantDataSyncJob(requestParameters: JobsApiCancelTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).cancelTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1CancelJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a Job.
     * @param {JobsApiCreateJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public createJob(requestParameters: JobsApiCreateJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).createJob(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsValidationsCreateValidationJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new DataSync job
     * @param {JobsApiCreateTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public createTenantDataSyncJob(requestParameters: JobsApiCreateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).createTenantDataSyncJob(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsCreateJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deactivate a DataSync job matching the primary key
     * @param {JobsApiDeactivateTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public deactivateTenantDataSyncJob(requestParameters: JobsApiDeactivateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).deactivateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1DeactivateJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a Job.
     * @param {JobsApiDeleteJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public deleteJob(requestParameters: JobsApiDeleteJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).deleteJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a DataSync job matching the primary key
     * @param {JobsApiDeleteTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public deleteTenantDataSyncJob(requestParameters: JobsApiDeleteTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).deleteTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Requests a Job execution.
     * @param {JobsApiExecuteJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public executeJob(requestParameters: JobsApiExecuteJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).executeJob(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Execute a DataSync job matching the primary key
     * @param {JobsApiExecuteTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public executeTenantDataSyncJob(requestParameters: JobsApiExecuteTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).executeTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.dataSyncApiJobV1ExecuteJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of DataSync Jobs
     * @param {JobsApiGetAllTenantDataSyncJobsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public getAllTenantDataSyncJobs(requestParameters: JobsApiGetAllTenantDataSyncJobsRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).getAllTenantDataSyncJobs(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a Job by ID.
     * @param {JobsApiGetJobByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public getJobById(requestParameters: JobsApiGetJobByIdRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).getJobById(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of Jobs.
     * @param {JobsApiGetJobsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public getJobs(requestParameters: JobsApiGetJobsRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).getJobs(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a specific DataSync job using its primary key
     * @param {JobsApiGetTenantDataSyncJobProfileByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public getTenantDataSyncJobProfileById(requestParameters: JobsApiGetTenantDataSyncJobProfileByIdRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).getTenantDataSyncJobProfileById(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Requests a Job schedule restart.
     * @param {JobsApiRestartJobScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public restartJobSchedule(requestParameters: JobsApiRestartJobScheduleRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).restartJobSchedule(requestParameters.tenantId, requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a Job.
     * @param {JobsApiUpdateJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public updateJob(requestParameters: JobsApiUpdateJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).updateJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateValidationJobRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a DataSync job matching the primary key
     * @param {JobsApiUpdateTenantDataSyncJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public updateTenantDataSyncJob(requestParameters: JobsApiUpdateTenantDataSyncJobRequest, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).updateTenantDataSyncJob(requestParameters.tenantId, requestParameters.jobId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsJobsUpdateJobRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

