/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDtoPaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { FormApiQuestionsV1QuestionCreatedResponse } from '../models';
// @ts-ignore
import type { FormApiQuestionsV1QuestionDeletedResponse } from '../models';
// @ts-ignore
import type { FormApiQuestionsV1QuestionUpdatedResponse } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcProblemDetails } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * QuestionsApi - axios parameter creator
 * @export
 */
export const QuestionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new Question for a given section
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuestion: async (tenantId: string, formId: string, sectionId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createQuestion', 'tenantId', tenantId)
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('createQuestion', 'formId', formId)
            // verify required parameter 'sectionId' is not null or undefined
            assertParamExists('createQuestion', 'sectionId', sectionId)
            const localVarPath = `/tenants/{tenantId}/forms/{formId}/sections/{sectionId}/questions`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"sectionId"}}`, encodeURIComponent(String(sectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion: async (tenantId: string, formId: string, sectionId: string, questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteQuestion', 'tenantId', tenantId)
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('deleteQuestion', 'formId', formId)
            // verify required parameter 'sectionId' is not null or undefined
            assertParamExists('deleteQuestion', 'sectionId', sectionId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('deleteQuestion', 'questionId', questionId)
            const localVarPath = `/tenants/{tenantId}/forms/{formId}/sections/{sectionId}/questions/{questionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"sectionId"}}`, encodeURIComponent(String(sectionId)))
                .replace(`{${"questionId"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion: async (tenantId: string, formId: string, sectionId: string, questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getQuestion', 'tenantId', tenantId)
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('getQuestion', 'formId', formId)
            // verify required parameter 'sectionId' is not null or undefined
            assertParamExists('getQuestion', 'sectionId', sectionId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getQuestion', 'questionId', questionId)
            const localVarPath = `/tenants/{tenantId}/forms/{formId}/sections/{sectionId}/questions/{questionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"sectionId"}}`, encodeURIComponent(String(sectionId)))
                .replace(`{${"questionId"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search Questions
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchQuestions: async (tenantId: string, formId: string, sectionId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('searchQuestions', 'tenantId', tenantId)
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('searchQuestions', 'formId', formId)
            // verify required parameter 'sectionId' is not null or undefined
            assertParamExists('searchQuestions', 'sectionId', sectionId)
            const localVarPath = `/tenants/{tenantId}/forms/{formId}/sections/{sectionId}/questions`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"sectionId"}}`, encodeURIComponent(String(sectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestion: async (tenantId: string, formId: string, sectionId: string, questionId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateQuestion', 'tenantId', tenantId)
            // verify required parameter 'formId' is not null or undefined
            assertParamExists('updateQuestion', 'formId', formId)
            // verify required parameter 'sectionId' is not null or undefined
            assertParamExists('updateQuestion', 'sectionId', sectionId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('updateQuestion', 'questionId', questionId)
            const localVarPath = `/tenants/{tenantId}/forms/{formId}/sections/{sectionId}/questions/{questionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"formId"}}`, encodeURIComponent(String(formId)))
                .replace(`{${"sectionId"}}`, encodeURIComponent(String(sectionId)))
                .replace(`{${"questionId"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionsApi - functional programming interface
 * @export
 */
export const QuestionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a new Question for a given section
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuestion(tenantId: string, formId: string, sectionId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormApiQuestionsV1QuestionCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createQuestion(tenantId, formId, sectionId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.createQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQuestion(tenantId: string, formId: string, sectionId: string, questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormApiQuestionsV1QuestionDeletedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQuestion(tenantId, formId, sectionId, questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.deleteQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestion(tenantId: string, formId: string, sectionId: string, questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestion(tenantId, formId, sectionId, questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.getQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search Questions
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchQuestions(tenantId: string, formId: string, sectionId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDtoPaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchQuestions(tenantId, formId, sectionId, pageSize, pageIndex, orderBy, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.searchQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a Question.
         * @param {string} tenantId 
         * @param {string} formId 
         * @param {string} sectionId 
         * @param {string} questionId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuestion(tenantId: string, formId: string, sectionId: string, questionId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormApiQuestionsV1QuestionUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuestion(tenantId, formId, sectionId, questionId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.updateQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionsApi - factory interface
 * @export
 */
export const QuestionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a new Question for a given section
         * @param {QuestionsApiCreateQuestionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuestion(requestParameters: QuestionsApiCreateQuestionRequest, options?: RawAxiosRequestConfig): AxiosPromise<FormApiQuestionsV1QuestionCreatedResponse> {
            return localVarFp.createQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a Question.
         * @param {QuestionsApiDeleteQuestionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion(requestParameters: QuestionsApiDeleteQuestionRequest, options?: RawAxiosRequestConfig): AxiosPromise<FormApiQuestionsV1QuestionDeletedResponse> {
            return localVarFp.deleteQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Question.
         * @param {QuestionsApiGetQuestionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion(requestParameters: QuestionsApiGetQuestionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDto> {
            return localVarFp.getQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search Questions
         * @param {QuestionsApiSearchQuestionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchQuestions(requestParameters: QuestionsApiSearchQuestionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesFormsQuestionResponseDtoPaginatedItemsViewModel> {
            return localVarFp.searchQuestions(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a Question.
         * @param {QuestionsApiUpdateQuestionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestion(requestParameters: QuestionsApiUpdateQuestionRequest, options?: RawAxiosRequestConfig): AxiosPromise<FormApiQuestionsV1QuestionUpdatedResponse> {
            return localVarFp.updateQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createQuestion operation in QuestionsApi.
 * @export
 * @interface QuestionsApiCreateQuestionRequest
 */
export interface QuestionsApiCreateQuestionRequest {
    /**
     * 
     * @type {string}
     * @memberof QuestionsApiCreateQuestion
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiCreateQuestion
     */
    readonly formId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiCreateQuestion
     */
    readonly sectionId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto}
     * @memberof QuestionsApiCreateQuestion
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto
}

/**
 * Request parameters for deleteQuestion operation in QuestionsApi.
 * @export
 * @interface QuestionsApiDeleteQuestionRequest
 */
export interface QuestionsApiDeleteQuestionRequest {
    /**
     * 
     * @type {string}
     * @memberof QuestionsApiDeleteQuestion
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiDeleteQuestion
     */
    readonly formId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiDeleteQuestion
     */
    readonly sectionId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiDeleteQuestion
     */
    readonly questionId: string
}

/**
 * Request parameters for getQuestion operation in QuestionsApi.
 * @export
 * @interface QuestionsApiGetQuestionRequest
 */
export interface QuestionsApiGetQuestionRequest {
    /**
     * 
     * @type {string}
     * @memberof QuestionsApiGetQuestion
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiGetQuestion
     */
    readonly formId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiGetQuestion
     */
    readonly sectionId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiGetQuestion
     */
    readonly questionId: string
}

/**
 * Request parameters for searchQuestions operation in QuestionsApi.
 * @export
 * @interface QuestionsApiSearchQuestionsRequest
 */
export interface QuestionsApiSearchQuestionsRequest {
    /**
     * 
     * @type {string}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly formId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly sectionId: string

    /**
     * 
     * @type {number}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly orderBy?: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiSearchQuestions
     */
    readonly filter?: string
}

/**
 * Request parameters for updateQuestion operation in QuestionsApi.
 * @export
 * @interface QuestionsApiUpdateQuestionRequest
 */
export interface QuestionsApiUpdateQuestionRequest {
    /**
     * 
     * @type {string}
     * @memberof QuestionsApiUpdateQuestion
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiUpdateQuestion
     */
    readonly formId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiUpdateQuestion
     */
    readonly sectionId: string

    /**
     * 
     * @type {string}
     * @memberof QuestionsApiUpdateQuestion
     */
    readonly questionId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto}
     * @memberof QuestionsApiUpdateQuestion
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
}

/**
 * QuestionsApi - object-oriented interface
 * @export
 * @class QuestionsApi
 * @extends {BaseAPI}
 */
export class QuestionsApi extends BaseAPI {
    /**
     * 
     * @summary Creates a new Question for a given section
     * @param {QuestionsApiCreateQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    public createQuestion(requestParameters: QuestionsApiCreateQuestionRequest, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).createQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsCreateQuestionRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a Question.
     * @param {QuestionsApiDeleteQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    public deleteQuestion(requestParameters: QuestionsApiDeleteQuestionRequest, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).deleteQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Question.
     * @param {QuestionsApiGetQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    public getQuestion(requestParameters: QuestionsApiGetQuestionRequest, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).getQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search Questions
     * @param {QuestionsApiSearchQuestionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    public searchQuestions(requestParameters: QuestionsApiSearchQuestionsRequest, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).searchQuestions(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a Question.
     * @param {QuestionsApiUpdateQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    public updateQuestion(requestParameters: QuestionsApiUpdateQuestionRequest, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).updateQuestion(requestParameters.tenantId, requestParameters.formId, requestParameters.sectionId, requestParameters.questionId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

