/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
// @ts-ignore
import type { TenantApiTenantV1TenantSettingTypesListResponsePaginatedItemsViewModel } from '../models';
/**
 * TenantSettingTypesApi - axios parameter creator
 * @export
 */
export const TenantSettingTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieves all setting types
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSettingTypes: async (tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getAllSettingTypes', 'tenantId', tenantId)
            const localVarPath = `/tenants/settings`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantSettingTypesApi - functional programming interface
 * @export
 */
export const TenantSettingTypesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TenantSettingTypesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieves all setting types
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSettingTypes(tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1TenantSettingTypesListResponsePaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSettingTypes(tenantId, pageSize, pageIndex, orderBy, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantSettingTypesApi.getAllSettingTypes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TenantSettingTypesApi - factory interface
 * @export
 */
export const TenantSettingTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TenantSettingTypesApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieves all setting types
         * @param {TenantSettingTypesApiGetAllSettingTypesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSettingTypes(requestParameters: TenantSettingTypesApiGetAllSettingTypesRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1TenantSettingTypesListResponsePaginatedItemsViewModel> {
            return localVarFp.getAllSettingTypes(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllSettingTypes operation in TenantSettingTypesApi.
 * @export
 * @interface TenantSettingTypesApiGetAllSettingTypesRequest
 */
export interface TenantSettingTypesApiGetAllSettingTypesRequest {
    /**
     * 
     * @type {string}
     * @memberof TenantSettingTypesApiGetAllSettingTypes
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof TenantSettingTypesApiGetAllSettingTypes
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof TenantSettingTypesApiGetAllSettingTypes
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {string}
     * @memberof TenantSettingTypesApiGetAllSettingTypes
     */
    readonly orderBy?: string

    /**
     * 
     * @type {string}
     * @memberof TenantSettingTypesApiGetAllSettingTypes
     */
    readonly filter?: string
}

/**
 * TenantSettingTypesApi - object-oriented interface
 * @export
 * @class TenantSettingTypesApi
 * @extends {BaseAPI}
 */
export class TenantSettingTypesApi extends BaseAPI {
    /**
     * 
     * @summary Retrieves all setting types
     * @param {TenantSettingTypesApiGetAllSettingTypesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantSettingTypesApi
     */
    public getAllSettingTypes(requestParameters: TenantSettingTypesApiGetAllSettingTypesRequest, options?: RawAxiosRequestConfig) {
        return TenantSettingTypesApiFp(this.configuration).getAllSettingTypes(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }
}

