/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesTenantStatus } from './ed-graph-platform-http-aggregators-tenant-api-controllers-v1-view-models-responses-tenant-status';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenantLicense } from './ed-graph-platform-http-aggregators-tenant-api-controllers-v1-view-models-responses-user-tenant-license';

/**
 * 
 * @export
 * @interface EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant
 */
export interface EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant {
    /**
     * 
     * @type {string}
     * @memberof EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesTenantStatus}
     * @memberof EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant
     */
    'status'?: EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesTenantStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant
     */
    'roles'?: Array<string> | null;
    /**
     * 
     * @type {Array<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenantLicense>}
     * @memberof EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenant
     */
    'licenses'?: Array<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserTenantLicense> | null;
}



