/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TenantApiTenantV1LicenseType = {
    Unknown: 'Unknown',
    Full: 'Full',
    Trial: 'Trial'
} as const;

export type TenantApiTenantV1LicenseType = typeof TenantApiTenantV1LicenseType[keyof typeof TenantApiTenantV1LicenseType];



