/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnalyticsApiConfigurationsV1AnalyticsConfiguration } from './analytics-api-configurations-v1-analytics-configuration';

/**
 * 
 * @export
 * @interface AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel
 */
export interface AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel
     */
    'count'?: number;
    /**
     * 
     * @type {Array<AnalyticsApiConfigurationsV1AnalyticsConfiguration>}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsConfigurationPaginatedItemsViewModel
     */
    'data'?: Array<AnalyticsApiConfigurationsV1AnalyticsConfiguration> | null;
}

