/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1ChildJob } from './data-sync-api-job-v1-child-job';
// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1JobExecutionStatus } from './data-sync-api-job-v1-job-execution-status';
// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1JobStatus } from './data-sync-api-job-v1-job-status';
// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1Metric } from './data-sync-api-job-v1-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1Schedule } from './data-sync-api-job-v1-schedule';

/**
 * 
 * @export
 * @interface DataSyncApiJobV1JobListResponse
 */
export interface DataSyncApiJobV1JobListResponse {
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobTypeId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobTypeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'sourceConnectionId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'destinationConnectionId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'profileId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'applicationId'?: string | null;
    /**
     * 
     * @type {DataSyncApiJobV1Schedule}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'schedule'?: DataSyncApiJobV1Schedule;
    /**
     * 
     * @type {DataSyncApiJobV1JobStatus}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobStatus'?: DataSyncApiJobV1JobStatus;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobExecutionId'?: string | null;
    /**
     * 
     * @type {DataSyncApiJobV1JobExecutionStatus}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobExecutionStatus'?: DataSyncApiJobV1JobExecutionStatus;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobExecutionStartDateTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobExecutionEndDateTime'?: string | null;
    /**
     * 
     * @type {Array<DataSyncApiJobV1Metric>}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'metrics'?: Array<DataSyncApiJobV1Metric> | null;
    /**
     * 
     * @type {Array<DataSyncApiJobV1ChildJob>}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'childJobs'?: Array<DataSyncApiJobV1ChildJob> | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'createdDateTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'lastModifiedDateTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiJobV1JobListResponse
     */
    'jobExecutionQueuedDateTime'?: string | null;
}



