/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest
 */
export interface EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest {
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest
     */
    'environmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest
     */
    'reportingPeriodId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EdGraphServicesStateReportingV1SetReportingPeriodCurrentStepRequest
     */
    'number'?: number | null;
}

