/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1SyncEntry } from './edfi-admin-api-edfi-admin-v1-sync-entry';

/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
 */
export interface EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'instanceId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'year'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'edOrgId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'edOrgGuid'?: string | null;
    /**
     * 
     * @type {Array<EdfiAdminApiEdfiAdminV1SyncEntry>}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'entries'?: Array<EdfiAdminApiEdfiAdminV1SyncEntry> | null;
    /**
     * 
     * @type {boolean}
     * @memberof EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
     */
    'assignToExistingApplications'?: boolean;
}

