/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1ApplicationEndpoint
 */
export interface EdfiAdminApiEdfiAdminV1ApplicationEndpoint {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1ApplicationEndpoint
     */
    'accessType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1ApplicationEndpoint
     */
    'url'?: string | null;
}

