/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FormApiFormsV1FullFormUpdatedResponse
 */
export interface FormApiFormsV1FullFormUpdatedResponse {
    /**
     * 
     * @type {string}
     * @memberof FormApiFormsV1FullFormUpdatedResponse
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FormApiFormsV1FullFormUpdatedResponse
     */
    'tenantId'?: string | null;
}

