/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityApiUserV1LicenseAssignedResponse
 */
export interface IdentityApiUserV1LicenseAssignedResponse {
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1LicenseAssignedResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1LicenseAssignedResponse
     */
    'subscriptionId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1LicenseAssignedResponse
     */
    'applicationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1LicenseAssignedResponse
     */
    'userId'?: string | null;
}

