/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiStaffClassificationV1StaffClassificationResponse } from './identity-api-staff-classification-v1-staff-classification-response';

/**
 * 
 * @export
 * @interface IdentityApiStaffClassificationV1GetStaffClassificationsResponse
 */
export interface IdentityApiStaffClassificationV1GetStaffClassificationsResponse {
    /**
     * 
     * @type {number}
     * @memberof IdentityApiStaffClassificationV1GetStaffClassificationsResponse
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof IdentityApiStaffClassificationV1GetStaffClassificationsResponse
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof IdentityApiStaffClassificationV1GetStaffClassificationsResponse
     */
    'count'?: number;
    /**
     * 
     * @type {Array<IdentityApiStaffClassificationV1StaffClassificationResponse>}
     * @memberof IdentityApiStaffClassificationV1GetStaffClassificationsResponse
     */
    'data'?: Array<IdentityApiStaffClassificationV1StaffClassificationResponse> | null;
}

