/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityApiUserV1SEOAAAddedResponse
 */
export interface IdentityApiUserV1SEOAAAddedResponse {
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1SEOAAAddedResponse
     */
    'userId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1SEOAAAddedResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiUserV1SEOAAAddedResponse
     */
    'seoaaId'?: string | null;
}

