/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IMSAdminApiV1InstancesInstanceTruncatedResponse
 */
export interface IMSAdminApiV1InstancesInstanceTruncatedResponse {
    /**
     * 
     * @type {string}
     * @memberof IMSAdminApiV1InstancesInstanceTruncatedResponse
     */
    'instanceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IMSAdminApiV1InstancesInstanceTruncatedResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IMSAdminApiV1InstancesInstanceTruncatedResponse
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IMSAdminApiV1InstancesInstanceTruncatedResponse
     */
    'details'?: string | null;
}

