/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Webhook Subscribers
 * @export
 * @interface TenantApiWebhookV1WebhookSubscriberResponse
 */
export interface TenantApiWebhookV1WebhookSubscriberResponse {
    /**
     * 
     * @type {string}
     * @memberof TenantApiWebhookV1WebhookSubscriberResponse
     */
    'eventName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantApiWebhookV1WebhookSubscriberResponse
     */
    'eventVersion'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantApiWebhookV1WebhookSubscriberResponse
     */
    'eventSchema'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantApiWebhookV1WebhookSubscriberResponse
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantApiWebhookV1WebhookSubscriberResponse
     */
    'scope'?: Array<string> | null;
}

