/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TenantApiSectionsV1SchoolListResponse } from './tenant-api-sections-v1-school-list-response';

/**
 * 
 * @export
 * @interface TenantApiSectionsV1PaginatedSchoolsResponse
 */
export interface TenantApiSectionsV1PaginatedSchoolsResponse {
    /**
     * 
     * @type {number}
     * @memberof TenantApiSectionsV1PaginatedSchoolsResponse
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof TenantApiSectionsV1PaginatedSchoolsResponse
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof TenantApiSectionsV1PaginatedSchoolsResponse
     */
    'count'?: number;
    /**
     * 
     * @type {Array<TenantApiSectionsV1SchoolListResponse>}
     * @memberof TenantApiSectionsV1PaginatedSchoolsResponse
     */
    'data'?: Array<TenantApiSectionsV1SchoolListResponse> | null;
}

