/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Api
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TenantApiSectionsV1GradeLevelListResponse
 */
export interface TenantApiSectionsV1GradeLevelListResponse {
    /**
     * 
     * @type {string}
     * @memberof TenantApiSectionsV1GradeLevelListResponse
     */
    'gradeLevelDescriptor'?: string | null;
}

