/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidationsApiReportingPeriodsV1SubmissionMetricsAddedBulkResponse
 */
export interface ValidationsApiReportingPeriodsV1SubmissionMetricsAddedBulkResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionMetricsAddedBulkResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionMetricsAddedBulkResponse
     */
    'reportingPeriodId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionMetricsAddedBulkResponse
     */
    'submissionId'?: string | null;
}

