/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * ConnectionsByTypeDEPRECATEDApi - axios parameter creator
 * @export
 */
export const ConnectionsByTypeDEPRECATEDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates or Update a Connection by ConnectionType.
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdateStateReportingConnectionByTypeV1: async (tenantId: string, connectionType: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createOrUpdateStateReportingConnectionByTypeV1', 'tenantId', tenantId)
            // verify required parameter 'connectionType' is not null or undefined
            assertParamExists('createOrUpdateStateReportingConnectionByTypeV1', 'connectionType', connectionType)
            const localVarPath = `/tenants/{tenantId}/statereporting/connectionsByType/{connectionType}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"connectionType"}}`, encodeURIComponent(String(connectionType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a Connection by Type
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStateReportingByTypeConnectionV1: async (tenantId: string, connectionType: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteStateReportingByTypeConnectionV1', 'tenantId', tenantId)
            // verify required parameter 'connectionType' is not null or undefined
            assertParamExists('deleteStateReportingByTypeConnectionV1', 'connectionType', connectionType)
            const localVarPath = `/tenants/{tenantId}/statereporting/connectionsByType/{connectionType}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"connectionType"}}`, encodeURIComponent(String(connectionType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a Connection by Type.
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateReportingConnectionByTypeV1: async (tenantId: string, connectionType: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getStateReportingConnectionByTypeV1', 'tenantId', tenantId)
            // verify required parameter 'connectionType' is not null or undefined
            assertParamExists('getStateReportingConnectionByTypeV1', 'connectionType', connectionType)
            const localVarPath = `/tenants/{tenantId}/statereporting/connectionsByType/{connectionType}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"connectionType"}}`, encodeURIComponent(String(connectionType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConnectionsByTypeDEPRECATEDApi - functional programming interface
 * @export
 */
export const ConnectionsByTypeDEPRECATEDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConnectionsByTypeDEPRECATEDApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates or Update a Connection by ConnectionType.
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdateStateReportingConnectionByTypeV1(tenantId: string, connectionType: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdateStateReportingConnectionByTypeV1(tenantId, connectionType, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectionsByTypeDEPRECATEDApi.createOrUpdateStateReportingConnectionByTypeV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a Connection by Type
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStateReportingByTypeConnectionV1(tenantId: string, connectionType: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStateReportingByTypeConnectionV1(tenantId, connectionType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectionsByTypeDEPRECATEDApi.deleteStateReportingByTypeConnectionV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a Connection by Type.
         * @param {string} tenantId 
         * @param {string} connectionType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStateReportingConnectionByTypeV1(tenantId: string, connectionType: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStateReportingConnectionByTypeV1(tenantId, connectionType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectionsByTypeDEPRECATEDApi.getStateReportingConnectionByTypeV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConnectionsByTypeDEPRECATEDApi - factory interface
 * @export
 */
export const ConnectionsByTypeDEPRECATEDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConnectionsByTypeDEPRECATEDApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates or Update a Connection by ConnectionType.
         * @param {ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdateStateReportingConnectionByTypeV1(requestParameters: ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse> {
            return localVarFp.createOrUpdateStateReportingConnectionByTypeV1(requestParameters.tenantId, requestParameters.connectionType, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a Connection by Type
         * @param {ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStateReportingByTypeConnectionV1(requestParameters: ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse> {
            return localVarFp.deleteStateReportingByTypeConnectionV1(requestParameters.tenantId, requestParameters.connectionType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a Connection by Type.
         * @param {ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateReportingConnectionByTypeV1(requestParameters: ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse> {
            return localVarFp.getStateReportingConnectionByTypeV1(requestParameters.tenantId, requestParameters.connectionType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOrUpdateStateReportingConnectionByTypeV1 operation in ConnectionsByTypeDEPRECATEDApi.
 * @export
 * @interface ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request
 */
export interface ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request {
    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1
     */
    readonly connectionType: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest}
     * @memberof ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1
     */
    readonly edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest
}

/**
 * Request parameters for deleteStateReportingByTypeConnectionV1 operation in ConnectionsByTypeDEPRECATEDApi.
 * @export
 * @interface ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request
 */
export interface ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request {
    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1
     */
    readonly connectionType: string
}

/**
 * Request parameters for getStateReportingConnectionByTypeV1 operation in ConnectionsByTypeDEPRECATEDApi.
 * @export
 * @interface ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request
 */
export interface ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request {
    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1
     */
    readonly connectionType: string
}

/**
 * ConnectionsByTypeDEPRECATEDApi - object-oriented interface
 * @export
 * @class ConnectionsByTypeDEPRECATEDApi
 * @extends {BaseAPI}
 */
export class ConnectionsByTypeDEPRECATEDApi extends BaseAPI {
    /**
     * 
     * @summary Creates or Update a Connection by ConnectionType.
     * @param {ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectionsByTypeDEPRECATEDApi
     */
    public createOrUpdateStateReportingConnectionByTypeV1(requestParameters: ConnectionsByTypeDEPRECATEDApiCreateOrUpdateStateReportingConnectionByTypeV1Request, options?: RawAxiosRequestConfig) {
        return ConnectionsByTypeDEPRECATEDApiFp(this.configuration).createOrUpdateStateReportingConnectionByTypeV1(requestParameters.tenantId, requestParameters.connectionType, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a Connection by Type
     * @param {ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectionsByTypeDEPRECATEDApi
     */
    public deleteStateReportingByTypeConnectionV1(requestParameters: ConnectionsByTypeDEPRECATEDApiDeleteStateReportingByTypeConnectionV1Request, options?: RawAxiosRequestConfig) {
        return ConnectionsByTypeDEPRECATEDApiFp(this.configuration).deleteStateReportingByTypeConnectionV1(requestParameters.tenantId, requestParameters.connectionType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a Connection by Type.
     * @param {ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectionsByTypeDEPRECATEDApi
     */
    public getStateReportingConnectionByTypeV1(requestParameters: ConnectionsByTypeDEPRECATEDApiGetStateReportingConnectionByTypeV1Request, options?: RawAxiosRequestConfig) {
        return ConnectionsByTypeDEPRECATEDApiFp(this.configuration).getStateReportingConnectionByTypeV1(requestParameters.tenantId, requestParameters.connectionType, options).then((request) => request(this.axios, this.basePath));
    }
}

