/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionUpdatedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1PagedConnectionsResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * EnvironmentsConnectionsApi - axios parameter creator
 * @export
 */
export const EnvironmentsConnectionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStateReportingConnection: async (tenantId: string, environmentId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createStateReportingConnection', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('createStateReportingConnection', 'environmentId', environmentId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStateReportingConnection: async (tenantId: string, environmentId: string, connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteStateReportingConnection', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('deleteStateReportingConnection', 'environmentId', environmentId)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('deleteStateReportingConnection', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections/{connectionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of Connections.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} [instanceType] 
         * @param {string} [connectionType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findStateReportingConnections: async (tenantId: string, environmentId: string, instanceType?: string, connectionType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('findStateReportingConnections', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('findStateReportingConnections', 'environmentId', environmentId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (instanceType !== undefined) {
                localVarQueryParameter['instanceType'] = instanceType;
            }

            if (connectionType !== undefined) {
                localVarQueryParameter['connectionType'] = connectionType;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a Connection by ID.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateReportingConnection: async (tenantId: string, environmentId: string, connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getStateReportingConnection', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('getStateReportingConnection', 'environmentId', environmentId)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('getStateReportingConnection', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections/{connectionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Tests a Connection by ID.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testStateReportingConnectionById: async (tenantId: string, environmentId: string, connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('testStateReportingConnectionById', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('testStateReportingConnectionById', 'environmentId', environmentId)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('testStateReportingConnectionById', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections/{connectionId}/testconnection`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Tests a Connection by Type.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testStateReportingConnectionByType: async (tenantId: string, environmentId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('testStateReportingConnectionByType', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('testStateReportingConnectionByType', 'environmentId', environmentId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections/testconnection`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStateReportingConnection: async (tenantId: string, environmentId: string, connectionId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateStateReportingConnection', 'tenantId', tenantId)
            // verify required parameter 'environmentId' is not null or undefined
            assertParamExists('updateStateReportingConnection', 'environmentId', environmentId)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('updateStateReportingConnection', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/statereporting/environments/{environmentId}/connections/{connectionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"environmentId"}}`, encodeURIComponent(String(environmentId)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnvironmentsConnectionsApi - functional programming interface
 * @export
 */
export const EnvironmentsConnectionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnvironmentsConnectionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a new Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStateReportingConnection(tenantId: string, environmentId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStateReportingConnection(tenantId, environmentId, edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.createStateReportingConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStateReportingConnection(tenantId: string, environmentId: string, connectionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStateReportingConnection(tenantId, environmentId, connectionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.deleteStateReportingConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a list of Connections.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} [instanceType] 
         * @param {string} [connectionType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findStateReportingConnections(tenantId: string, environmentId: string, instanceType?: string, connectionType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1PagedConnectionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findStateReportingConnections(tenantId, environmentId, instanceType, connectionType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.findStateReportingConnections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieves a Connection by ID.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStateReportingConnection(tenantId: string, environmentId: string, connectionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStateReportingConnection(tenantId, environmentId, connectionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.getStateReportingConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Tests a Connection by ID.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testStateReportingConnectionById(tenantId: string, environmentId: string, connectionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testStateReportingConnectionById(tenantId, environmentId, connectionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.testStateReportingConnectionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Tests a Connection by Type.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testStateReportingConnectionByType(tenantId: string, environmentId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testStateReportingConnectionByType(tenantId, environmentId, edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.testStateReportingConnectionByType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a Connection.
         * @param {string} tenantId 
         * @param {string} environmentId 
         * @param {string} connectionId 
         * @param {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest} [edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStateReportingConnection(tenantId: string, environmentId: string, connectionId: string, edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStateReportingConnection(tenantId, environmentId, connectionId, edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnvironmentsConnectionsApi.updateStateReportingConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnvironmentsConnectionsApi - factory interface
 * @export
 */
export const EnvironmentsConnectionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnvironmentsConnectionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a new Connection.
         * @param {EnvironmentsConnectionsApiCreateStateReportingConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStateReportingConnection(requestParameters: EnvironmentsConnectionsApiCreateStateReportingConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionCreatedResponse> {
            return localVarFp.createStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a Connection.
         * @param {EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStateReportingConnection(requestParameters: EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionDeletedResponse> {
            return localVarFp.deleteStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of Connections.
         * @param {EnvironmentsConnectionsApiFindStateReportingConnectionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findStateReportingConnections(requestParameters: EnvironmentsConnectionsApiFindStateReportingConnectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1PagedConnectionsResponse> {
            return localVarFp.findStateReportingConnections(requestParameters.tenantId, requestParameters.environmentId, requestParameters.instanceType, requestParameters.connectionType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a Connection by ID.
         * @param {EnvironmentsConnectionsApiGetStateReportingConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStateReportingConnection(requestParameters: EnvironmentsConnectionsApiGetStateReportingConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionProfileResponse> {
            return localVarFp.getStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Tests a Connection by ID.
         * @param {EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testStateReportingConnectionById(requestParameters: EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionResponse> {
            return localVarFp.testStateReportingConnectionById(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Tests a Connection by Type.
         * @param {EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testStateReportingConnectionByType(requestParameters: EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionResponse> {
            return localVarFp.testStateReportingConnectionByType(requestParameters.tenantId, requestParameters.environmentId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a Connection.
         * @param {EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStateReportingConnection(requestParameters: EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesStateReportingV1ConnectionUpdatedResponse> {
            return localVarFp.updateStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createStateReportingConnection operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiCreateStateReportingConnectionRequest
 */
export interface EnvironmentsConnectionsApiCreateStateReportingConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiCreateStateReportingConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiCreateStateReportingConnection
     */
    readonly environmentId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest}
     * @memberof EnvironmentsConnectionsApiCreateStateReportingConnection
     */
    readonly edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest
}

/**
 * Request parameters for deleteStateReportingConnection operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest
 */
export interface EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiDeleteStateReportingConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiDeleteStateReportingConnection
     */
    readonly environmentId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiDeleteStateReportingConnection
     */
    readonly connectionId: string
}

/**
 * Request parameters for findStateReportingConnections operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiFindStateReportingConnectionsRequest
 */
export interface EnvironmentsConnectionsApiFindStateReportingConnectionsRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiFindStateReportingConnections
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiFindStateReportingConnections
     */
    readonly environmentId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiFindStateReportingConnections
     */
    readonly instanceType?: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiFindStateReportingConnections
     */
    readonly connectionType?: string
}

/**
 * Request parameters for getStateReportingConnection operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiGetStateReportingConnectionRequest
 */
export interface EnvironmentsConnectionsApiGetStateReportingConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiGetStateReportingConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiGetStateReportingConnection
     */
    readonly environmentId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiGetStateReportingConnection
     */
    readonly connectionId: string
}

/**
 * Request parameters for testStateReportingConnectionById operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest
 */
export interface EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionById
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionById
     */
    readonly environmentId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionById
     */
    readonly connectionId: string
}

/**
 * Request parameters for testStateReportingConnectionByType operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest
 */
export interface EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionByType
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionByType
     */
    readonly environmentId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest}
     * @memberof EnvironmentsConnectionsApiTestStateReportingConnectionByType
     */
    readonly edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest
}

/**
 * Request parameters for updateStateReportingConnection operation in EnvironmentsConnectionsApi.
 * @export
 * @interface EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest
 */
export interface EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiUpdateStateReportingConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiUpdateStateReportingConnection
     */
    readonly environmentId: string

    /**
     * 
     * @type {string}
     * @memberof EnvironmentsConnectionsApiUpdateStateReportingConnection
     */
    readonly connectionId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest}
     * @memberof EnvironmentsConnectionsApiUpdateStateReportingConnection
     */
    readonly edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest?: EdGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest
}

/**
 * EnvironmentsConnectionsApi - object-oriented interface
 * @export
 * @class EnvironmentsConnectionsApi
 * @extends {BaseAPI}
 */
export class EnvironmentsConnectionsApi extends BaseAPI {
    /**
     * 
     * @summary Creates a new Connection.
     * @param {EnvironmentsConnectionsApiCreateStateReportingConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public createStateReportingConnection(requestParameters: EnvironmentsConnectionsApiCreateStateReportingConnectionRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).createStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1CreateConnectionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a Connection.
     * @param {EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public deleteStateReportingConnection(requestParameters: EnvironmentsConnectionsApiDeleteStateReportingConnectionRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).deleteStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of Connections.
     * @param {EnvironmentsConnectionsApiFindStateReportingConnectionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public findStateReportingConnections(requestParameters: EnvironmentsConnectionsApiFindStateReportingConnectionsRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).findStateReportingConnections(requestParameters.tenantId, requestParameters.environmentId, requestParameters.instanceType, requestParameters.connectionType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a Connection by ID.
     * @param {EnvironmentsConnectionsApiGetStateReportingConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public getStateReportingConnection(requestParameters: EnvironmentsConnectionsApiGetStateReportingConnectionRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).getStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Tests a Connection by ID.
     * @param {EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public testStateReportingConnectionById(requestParameters: EnvironmentsConnectionsApiTestStateReportingConnectionByIdRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).testStateReportingConnectionById(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Tests a Connection by Type.
     * @param {EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public testStateReportingConnectionByType(requestParameters: EnvironmentsConnectionsApiTestStateReportingConnectionByTypeRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).testStateReportingConnectionByType(requestParameters.tenantId, requestParameters.environmentId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a Connection.
     * @param {EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvironmentsConnectionsApi
     */
    public updateStateReportingConnection(requestParameters: EnvironmentsConnectionsApiUpdateStateReportingConnectionRequest, options?: RawAxiosRequestConfig) {
        return EnvironmentsConnectionsApiFp(this.configuration).updateStateReportingConnection(requestParameters.tenantId, requestParameters.environmentId, requestParameters.connectionId, requestParameters.edGraphHttpAggregatorsTenantApiServicesStateReportingV1UpdateConnectionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

