/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionCreatedResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionResponse } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionUpdatedResponse } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * OnboardingStepsConnectionsApi - axios parameter creator
 * @export
 */
export const OnboardingStepsConnectionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates an Onboarding Step connection.
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOnboardingStepConnection: async (tenantId: string, stepNumber: number, body?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createOnboardingStepConnection', 'tenantId', tenantId)
            // verify required parameter 'stepNumber' is not null or undefined
            assertParamExists('createOnboardingStepConnection', 'stepNumber', stepNumber)
            const localVarPath = `/tenants/{tenantId}/onboardingsteps/{stepNumber}/connections`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"stepNumber"}}`, encodeURIComponent(String(stepNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an Onboarding Step connection by Id
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOnboardingStepConnectionById: async (tenantId: string, stepNumber: number, connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getOnboardingStepConnectionById', 'tenantId', tenantId)
            // verify required parameter 'stepNumber' is not null or undefined
            assertParamExists('getOnboardingStepConnectionById', 'stepNumber', stepNumber)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('getOnboardingStepConnectionById', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/onboardingsteps/{stepNumber}/connections/{connectionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"stepNumber"}}`, encodeURIComponent(String(stepNumber)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an Onboarding Step connection by Id
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {string} connectionId 
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOnboardingStepConnection: async (tenantId: string, stepNumber: number, connectionId: string, body?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateOnboardingStepConnection', 'tenantId', tenantId)
            // verify required parameter 'stepNumber' is not null or undefined
            assertParamExists('updateOnboardingStepConnection', 'stepNumber', stepNumber)
            // verify required parameter 'connectionId' is not null or undefined
            assertParamExists('updateOnboardingStepConnection', 'connectionId', connectionId)
            const localVarPath = `/tenants/{tenantId}/onboardingsteps/{stepNumber}/connections/{connectionId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)))
                .replace(`{${"stepNumber"}}`, encodeURIComponent(String(stepNumber)))
                .replace(`{${"connectionId"}}`, encodeURIComponent(String(connectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OnboardingStepsConnectionsApi - functional programming interface
 * @export
 */
export const OnboardingStepsConnectionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OnboardingStepsConnectionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates an Onboarding Step connection.
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOnboardingStepConnection(tenantId: string, stepNumber: number, body?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOnboardingStepConnection(tenantId, stepNumber, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingStepsConnectionsApi.createOnboardingStepConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an Onboarding Step connection by Id
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {string} connectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOnboardingStepConnectionById(tenantId: string, stepNumber: number, connectionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOnboardingStepConnectionById(tenantId, stepNumber, connectionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingStepsConnectionsApi.getOnboardingStepConnectionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an Onboarding Step connection by Id
         * @param {string} tenantId 
         * @param {number} stepNumber 
         * @param {string} connectionId 
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOnboardingStepConnection(tenantId: string, stepNumber: number, connectionId: string, body?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOnboardingStepConnection(tenantId, stepNumber, connectionId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingStepsConnectionsApi.updateOnboardingStepConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OnboardingStepsConnectionsApi - factory interface
 * @export
 */
export const OnboardingStepsConnectionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OnboardingStepsConnectionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates an Onboarding Step connection.
         * @param {OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOnboardingStepConnection(requestParameters: OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionCreatedResponse> {
            return localVarFp.createOnboardingStepConnection(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an Onboarding Step connection by Id
         * @param {OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOnboardingStepConnectionById(requestParameters: OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionResponse> {
            return localVarFp.getOnboardingStepConnectionById(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.connectionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an Onboarding Step connection by Id
         * @param {OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOnboardingStepConnection(requestParameters: OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsConnectionUpdatedResponse> {
            return localVarFp.updateOnboardingStepConnection(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.connectionId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOnboardingStepConnection operation in OnboardingStepsConnectionsApi.
 * @export
 * @interface OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest
 */
export interface OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof OnboardingStepsConnectionsApiCreateOnboardingStepConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof OnboardingStepsConnectionsApiCreateOnboardingStepConnection
     */
    readonly stepNumber: number

    /**
     * 
     * @type {any}
     * @memberof OnboardingStepsConnectionsApiCreateOnboardingStepConnection
     */
    readonly body?: any
}

/**
 * Request parameters for getOnboardingStepConnectionById operation in OnboardingStepsConnectionsApi.
 * @export
 * @interface OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest
 */
export interface OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof OnboardingStepsConnectionsApiGetOnboardingStepConnectionById
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof OnboardingStepsConnectionsApiGetOnboardingStepConnectionById
     */
    readonly stepNumber: number

    /**
     * 
     * @type {string}
     * @memberof OnboardingStepsConnectionsApiGetOnboardingStepConnectionById
     */
    readonly connectionId: string
}

/**
 * Request parameters for updateOnboardingStepConnection operation in OnboardingStepsConnectionsApi.
 * @export
 * @interface OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest
 */
export interface OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof OnboardingStepsConnectionsApiUpdateOnboardingStepConnection
     */
    readonly tenantId: string

    /**
     * 
     * @type {number}
     * @memberof OnboardingStepsConnectionsApiUpdateOnboardingStepConnection
     */
    readonly stepNumber: number

    /**
     * 
     * @type {string}
     * @memberof OnboardingStepsConnectionsApiUpdateOnboardingStepConnection
     */
    readonly connectionId: string

    /**
     * 
     * @type {any}
     * @memberof OnboardingStepsConnectionsApiUpdateOnboardingStepConnection
     */
    readonly body?: any
}

/**
 * OnboardingStepsConnectionsApi - object-oriented interface
 * @export
 * @class OnboardingStepsConnectionsApi
 * @extends {BaseAPI}
 */
export class OnboardingStepsConnectionsApi extends BaseAPI {
    /**
     * 
     * @summary Creates an Onboarding Step connection.
     * @param {OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingStepsConnectionsApi
     */
    public createOnboardingStepConnection(requestParameters: OnboardingStepsConnectionsApiCreateOnboardingStepConnectionRequest, options?: RawAxiosRequestConfig) {
        return OnboardingStepsConnectionsApiFp(this.configuration).createOnboardingStepConnection(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an Onboarding Step connection by Id
     * @param {OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingStepsConnectionsApi
     */
    public getOnboardingStepConnectionById(requestParameters: OnboardingStepsConnectionsApiGetOnboardingStepConnectionByIdRequest, options?: RawAxiosRequestConfig) {
        return OnboardingStepsConnectionsApiFp(this.configuration).getOnboardingStepConnectionById(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.connectionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an Onboarding Step connection by Id
     * @param {OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingStepsConnectionsApi
     */
    public updateOnboardingStepConnection(requestParameters: OnboardingStepsConnectionsApiUpdateOnboardingStepConnectionRequest, options?: RawAxiosRequestConfig) {
        return OnboardingStepsConnectionsApiFp(this.configuration).updateOnboardingStepConnection(requestParameters.tenantId, requestParameters.stepNumber, requestParameters.connectionId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

