/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
// @ts-ignore
import type { TenantApiTenantV1TenantProfileResponse } from '../models';
// @ts-ignore
import type { TenantApiTenantV1TenantUpdatedResponse } from '../models';
/**
 * TenantsApi - axios parameter creator
 * @export
 */
export const TenantsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieves the profile of a specific tenant
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantByIdAsync: async (tenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getTenantByIdAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Note: Only the tenant\'s Identity Providers can be updated at this time
         * @summary Updates a tenant\'s profile
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantAsync: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateTenantAsync', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}`
                .replace(`{${"tenantId"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantsApi - functional programming interface
 * @export
 */
export const TenantsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TenantsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieves the profile of a specific tenant
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantByIdAsync(tenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1TenantProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantByIdAsync(tenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantsApi.getTenantByIdAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Note: Only the tenant\'s Identity Providers can be updated at this time
         * @summary Updates a tenant\'s profile
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTenantAsync(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantApiTenantV1TenantUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTenantAsync(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantsApi.updateTenantAsync']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TenantsApi - factory interface
 * @export
 */
export const TenantsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TenantsApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieves the profile of a specific tenant
         * @param {TenantsApiGetTenantByIdAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantByIdAsync(requestParameters: TenantsApiGetTenantByIdAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1TenantProfileResponse> {
            return localVarFp.getTenantByIdAsync(requestParameters.tenantId, options).then((request) => request(axios, basePath));
        },
        /**
         * Note: Only the tenant\'s Identity Providers can be updated at this time
         * @summary Updates a tenant\'s profile
         * @param {TenantsApiUpdateTenantAsyncRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantAsync(requestParameters: TenantsApiUpdateTenantAsyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<TenantApiTenantV1TenantUpdatedResponse> {
            return localVarFp.updateTenantAsync(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTenantByIdAsync operation in TenantsApi.
 * @export
 * @interface TenantsApiGetTenantByIdAsyncRequest
 */
export interface TenantsApiGetTenantByIdAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof TenantsApiGetTenantByIdAsync
     */
    readonly tenantId: string
}

/**
 * Request parameters for updateTenantAsync operation in TenantsApi.
 * @export
 * @interface TenantsApiUpdateTenantAsyncRequest
 */
export interface TenantsApiUpdateTenantAsyncRequest {
    /**
     * 
     * @type {string}
     * @memberof TenantsApiUpdateTenantAsync
     */
    readonly tenantId: string

    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest}
     * @memberof TenantsApiUpdateTenantAsync
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest
}

/**
 * TenantsApi - object-oriented interface
 * @export
 * @class TenantsApi
 * @extends {BaseAPI}
 */
export class TenantsApi extends BaseAPI {
    /**
     * 
     * @summary Retrieves the profile of a specific tenant
     * @param {TenantsApiGetTenantByIdAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantsApi
     */
    public getTenantByIdAsync(requestParameters: TenantsApiGetTenantByIdAsyncRequest, options?: RawAxiosRequestConfig) {
        return TenantsApiFp(this.configuration).getTenantByIdAsync(requestParameters.tenantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Note: Only the tenant\'s Identity Providers can be updated at this time
     * @summary Updates a tenant\'s profile
     * @param {TenantsApiUpdateTenantAsyncRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantsApi
     */
    public updateTenantAsync(requestParameters: TenantsApiUpdateTenantAsyncRequest, options?: RawAxiosRequestConfig) {
        return TenantsApiFp(this.configuration).updateTenantAsync(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsUpdateTenantRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

