/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnalyticsApiConfigurationsV1AnalyticsAzureAd
 */
export interface AnalyticsApiConfigurationsV1AnalyticsAzureAd {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsAzureAd
     */
    'clientId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsAzureAd
     */
    'azureTenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsAzureAd
     */
    'clientSecret'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsAzureAd
     */
    'scopes'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsApiConfigurationsV1AnalyticsAzureAd
     */
    'tenantId'?: string | null;
}

