/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataSyncApiDslV1UpdateJobRequest
 */
export interface DataSyncApiDslV1UpdateJobRequest {
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'jobId'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'enabled'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'dagWorkflow'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'startDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'cron'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSyncApiDslV1UpdateJobRequest
     */
    'timeZone'?: string | null;
}

