/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1DataRefreshType } from './data-sync-api-job-v1-data-refresh-type';
// May contain unused imports in some cases
// @ts-ignore
import type { DataSyncApiJobV1JobExecutionMetadata } from './data-sync-api-job-v1-job-execution-metadata';

export interface DataSyncApiJobV1ExecuteJobRequest {
    'tenantId'?: string | null;
    'jobId'?: string | null;
    'childJobId'?: string | null;
    'dataRefreshType'?: DataSyncApiJobV1DataRefreshType;
    'dataRefreshSpecificDate'?: string | null;
    'jobExecutionMetadata'?: Array<DataSyncApiJobV1JobExecutionMetadata> | null;
}



