/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsLicensesAssignLicenseRequest } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-requests-licenses-assign-license-request';

export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsCreateLocalUserRequest {
    'tenantId'?: string | null;
    'userName'?: string | null;
    'email'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'role'?: string | null;
    'phoneNumber'?: string | null;
    'lockoutEnabled'?: boolean;
    'password'?: string | null;
    'autoGeneratedPassword'?: boolean;
    'twoFactorEnabled'?: boolean;
    'assignLicenseRequests'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsLicensesAssignLicenseRequest> | null;
}

