/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdGraphServicesStateReportingV1UpdateEnvironmentRequest
 */
export interface EdGraphServicesStateReportingV1UpdateEnvironmentRequest {
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'environmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'dbEnvironmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'edFiInstanceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'mode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphServicesStateReportingV1UpdateEnvironmentRequest
     */
    'workspaceName'?: string | null;
}

