/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphServicesStateReportingV1DataUser } from './ed-graph-services-state-reporting-v1-data-user';

export interface EdGraphServicesStateReportingV1Category {
    'tenantId'?: string | null;
    'environmentId'?: string | null;
    'reportingPeriodId'?: string | null;
    'categoryId'?: string | null;
    'name'?: string | null;
    'description'?: string | null;
    'certificationStatus'?: string | null;
    'dataOwner'?: EdGraphServicesStateReportingV1DataUser;
    'dataStewards'?: Array<EdGraphServicesStateReportingV1DataUser> | null;
}

