/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphServicesStateReportingV1UpdateReportingPeriodBulkRequest Types ReportingPeriod } from './ed-graph-services-state-reporting-v1-update-reporting-period-bulk-request types reporting-period';

export interface EdGraphServicesStateReportingV1UpdateReportingPeriodBulkRequest {
    'tenantId'?: string | null;
    'environmentId'?: string | null;
    'reportingPeriods'?: Array<EdGraphServicesStateReportingV1UpdateReportingPeriodBulkRequest Types ReportingPeriod> | null;
}

