/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesApplicationRole {
    /**
     * The role associated with the application
     */
    'role'?: string | null;
    /**
     * Indicates if the user is assigned license for this application
     */
    'isAssigned'?: boolean;
}

