/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesObservationsPersonaResponse } from './ed-graph-http-aggregators-tenant-api-services-observations-persona-response';

export interface EdGraphHttpAggregatorsTenantApiServicesObservationsPersonaResponseGetPaginatedItemsResponse {
    'pageIndex'?: number;
    'pageSize'?: number;
    'data'?: Array<EdGraphHttpAggregatorsTenantApiServicesObservationsPersonaResponse> | null;
    'count'?: number;
}

