/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentResponseDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-contact-student-response-dto';

export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactResponseDto {
    'id'?: string | null;
    'tenantId'?: string | null;
    'contactId'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'email'?: string | null;
    'phone'?: string | null;
    'students'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentResponseDto> | null;
    'relationship'?: string | null;
    'studentCount'?: number;
    'isPhoneOverride'?: boolean | null;
    'isEmailOverride'?: boolean | null;
    'signInStatus'?: string | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'lastUpdatedDateTime'?: string | null;
    'isDeleted'?: boolean;
}

