/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiDataModel } from './ed-graph-http-aggregators-tenant-api-services-onboarding-steps-ed-fi-data-model';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsUrls } from './ed-graph-http-aggregators-tenant-api-services-onboarding-steps-urls';

/**
 * 
 * @export
 * @interface EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
 */
export interface EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi {
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'informationalVersion'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'suite'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'build'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'apiMode'?: string | null;
    /**
     * 
     * @type {Array<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiDataModel>}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'dataModels'?: Array<EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiDataModel> | null;
    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsUrls}
     * @memberof EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsEdFiApi
     */
    'urls'?: EdGraphHttpAggregatorsTenantApiServicesOnboardingStepsUrls;
}

