/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionValidationRequestDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-requests-forms-update-question-validation-request-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { FormApiQuestionsV1QuestionType } from './form-api-questions-v1-question-type';

/**
 * 
 * @export
 * @interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto {
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'formId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'sectionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {FormApiQuestionsV1QuestionType}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'type'?: FormApiQuestionsV1QuestionType;
    /**
     * 
     * @type {boolean}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'required'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'defaultValue'?: string | null;
    /**
     * 
     * @type {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionValidationRequestDto}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'validation'?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionValidationRequestDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'options'?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'order'?: number;
    /**
     * 
     * @type {any}
     * @memberof EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsFormsUpdateQuestionRequestDto
     */
    'component'?: any | null;
}



