/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EdfiAdminApiEdfiAdminV1EdFiApplicationListResponse {
    'tenantId'?: string | null;
    'applicationId'?: number;
    'applicationName'?: string | null;
    'claimSetName'?: string | null;
    'vendorId'?: number;
    'vendorName'?: string | null;
    'edOrgsCount'?: number;
    'operationalContextUri'?: string | null;
}

