/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry } from './edfi-admin-api-edfi-admin-v1-add-school-year-range-request-entry';

/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest
 */
export interface EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest
     */
    'instanceId'?: string | null;
    /**
     * 
     * @type {Array<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>}
     * @memberof EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest
     */
    'entries'?: Array<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry> | null;
}

