/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1EdFiConnectionTier } from './edfi-admin-api-edfi-admin-v1-ed-fi-connection-tier';
// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1InstanceType } from './edfi-admin-api-edfi-admin-v1-instance-type';

export interface EdfiAdminApiEdfiAdminV1EdFiConnection {
    'id'?: string | null;
    'connectionName'?: string | null;
    'databaseEngine'?: string | null;
    'edFiVersion'?: string | null;
    'edFiExtension'?: string | null;
    'hostingProvider'?: string | null;
    'allowedTenantIds'?: Array<string> | null;
    'tiers'?: Array<EdfiAdminApiEdfiAdminV1EdFiConnectionTier> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'connectionType'?: string | null;
    'instanceType'?: EdfiAdminApiEdfiAdminV1InstanceType;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
    'metadataJson'?: string | null;
}



