/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim {
    'resourceClaimId'?: number;
    'name'?: string | null;
    'create'?: boolean;
    'createAuthStrategy'?: string | null;
    'createAuthStrategyOverride'?: string | null;
    'read'?: boolean;
    'readAuthStrategy'?: string | null;
    'readAuthStrategyOverride'?: string | null;
    'update'?: boolean;
    'updateAuthStrategy'?: string | null;
    'updateAuthStrategyOverride'?: string | null;
    'delete'?: boolean;
    'deleteAuthStrategy'?: string | null;
    'deleteAuthStrategyOverride'?: string | null;
    'children'?: Array<EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim> | null;
    'readChanges'?: boolean;
    'readChangesAuthStrategy'?: string | null;
    'readChangesAuthStrategyOverride'?: string | null;
}

