/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1TierSqlConnection
 */
export interface EdfiAdminApiEdfiAdminV1TierSqlConnection {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'sqlServer'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'sqlServerUserName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'sqlServerPassword'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'azureSubscriptionId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'azureResourceGroupName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'azureServerName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierSqlConnection
     */
    'azureServerElasticPoolName'?: string | null;
}

