/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1OdsApiConnectionEndpoint } from './edfi-admin-api-edfi-admin-v1-ods-api-connection-endpoint';

/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel
 */
export interface EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel
     */
    'clientId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel
     */
    'tokenUrl'?: string | null;
    /**
     * 
     * @type {Array<EdfiAdminApiEdfiAdminV1OdsApiConnectionEndpoint>}
     * @memberof EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel
     */
    'endpoints'?: Array<EdfiAdminApiEdfiAdminV1OdsApiConnectionEndpoint> | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1TierOdsApiConnectionListModel
     */
    'metadataUrl'?: string | null;
}

