/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1DescriptorMapping } from './edfi-admin-api-edfi-admin-v1-descriptor-mapping';

/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse
 */
export interface EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse {
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse
     */
    'count'?: number;
    /**
     * 
     * @type {Array<EdfiAdminApiEdfiAdminV1DescriptorMapping>}
     * @memberof EdfiAdminApiEdfiAdminV1DescriptorMappingsPaginatedItemsResponse
     */
    'data'?: Array<EdfiAdminApiEdfiAdminV1DescriptorMapping> | null;
}

