/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
 */
export interface EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
     */
    'instanceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1CreateOnboardingStepRequest
     */
    'status'?: string | null;
}

