/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdfiAdminApiEdfiAdminV1SchoolCountRepresentation } from './edfi-admin-api-edfi-admin-v1-school-count-representation';

/**
 * 
 * @export
 * @interface EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse
 */
export interface EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse {
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse
     */
    'instanceId'?: string | null;
    /**
     * 
     * @type {Array<EdfiAdminApiEdfiAdminV1SchoolCountRepresentation>}
     * @memberof EdfiAdminApiEdfiAdminV1SchoolsByTypeReportResponse
     */
    'schoolCountRepresentations'?: Array<EdfiAdminApiEdfiAdminV1SchoolCountRepresentation> | null;
}

