/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FormApiQuestionsV1QuestionVisibilityRule } from './form-api-questions-v1-question-visibility-rule';

/**
 * 
 * @export
 * @interface FormApiQuestionsV1QuestionVisibilityCondition
 */
export interface FormApiQuestionsV1QuestionVisibilityCondition {
    /**
     * 
     * @type {string}
     * @memberof FormApiQuestionsV1QuestionVisibilityCondition
     */
    'logic'?: string | null;
    /**
     * 
     * @type {Array<FormApiQuestionsV1QuestionVisibilityRule>}
     * @memberof FormApiQuestionsV1QuestionVisibilityCondition
     */
    'rules'?: Array<FormApiQuestionsV1QuestionVisibilityRule> | null;
}

