/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const FormApiQuestionsV1QuestionType = {
    Unknown: 'Unknown',
    TextArea: 'TextArea',
    Select: 'Select',
    Date: 'Date',
    Radio: 'Radio',
    CustomComponent: 'CustomComponent',
    Scoring: 'Scoring',
    Html: 'Html',
    Image: 'Image',
} as const;

export type FormApiQuestionsV1QuestionType = typeof FormApiQuestionsV1QuestionType[keyof typeof FormApiQuestionsV1QuestionType];



