/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiInstructionalInsightsV1CallbackNotificationMessage } from './identity-api-instructional-insights-v1-callback-notification-message';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobInputMessage } from './identity-api-instructional-insights-v1-instructional-insights-security-sync-job-input-message';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiInstructionalInsightsV1RetryPolicyMessage } from './identity-api-instructional-insights-v1-retry-policy-message';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiInstructionalInsightsV1ScheduleMessage } from './identity-api-instructional-insights-v1-schedule-message';

/**
 * 
 * @export
 * @interface IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
 */
export interface IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest {
    /**
     * 
     * @type {string}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'jobId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobInputMessage}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'input'?: IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobInputMessage;
    /**
     * 
     * @type {IdentityApiInstructionalInsightsV1ScheduleMessage}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'schedule'?: IdentityApiInstructionalInsightsV1ScheduleMessage;
    /**
     * 
     * @type {IdentityApiInstructionalInsightsV1RetryPolicyMessage}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'retryPolicy'?: IdentityApiInstructionalInsightsV1RetryPolicyMessage;
    /**
     * 
     * @type {Array<IdentityApiInstructionalInsightsV1CallbackNotificationMessage>}
     * @memberof IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
     */
    'callbackNotifications'?: Array<IdentityApiInstructionalInsightsV1CallbackNotificationMessage> | null;
}

