/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiUserV1ComputedLicense } from './identity-api-user-v1-computed-license';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiUserV1EducationOrganization } from './identity-api-user-v1-education-organization';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiUserV1TenantSource } from './identity-api-user-v1-tenant-source';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiUserV1TenantStatus } from './identity-api-user-v1-tenant-status';

export interface IdentityApiUserV1Tenant {
    'tenantId'?: string | null;
    'status'?: IdentityApiUserV1TenantStatus;
    'source'?: IdentityApiUserV1TenantSource;
    'roles'?: Array<string> | null;
    /**
     * @deprecated
     */
    'educationOrganizations'?: Array<IdentityApiUserV1EducationOrganization> | null;
    'licenses'?: Array<IdentityApiUserV1ComputedLicense> | null;
    'organizationName'?: string | null;
}



