/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdentityApiApiClientV1ApiClientPaginatedItemsResponse } from './identity-api-api-client-v1-api-client-paginated-items-response';

/**
 * 
 * @export
 * @interface IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel
 */
export interface IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel {
    /**
     * 
     * @type {number}
     * @memberof IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel
     */
    'count'?: number;
    /**
     * 
     * @type {Array<IdentityApiApiClientV1ApiClientPaginatedItemsResponse>}
     * @memberof IdentityApiApiClientV1ApiClientPaginatedItemsResponsePaginatedItemsViewModel
     */
    'data'?: Array<IdentityApiApiClientV1ApiClientPaginatedItemsResponse> | null;
}

