/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const RegistrationApiRegistrationV2TenantType = {
    Unknown: 'Unknown',
    DataStandardGoverningBody: 'DataStandardGoverningBody',
    EducationalServiceAgency: 'EducationalServiceAgency',
    ImplementationPartner: 'ImplementationPartner',
    IndependentSoftwareVendor: 'IndependentSoftwareVendor',
    Internal: 'Internal',
    LocalEducationAgency: 'LocalEducationAgency',
    ManagedServiceProvider: 'ManagedServiceProvider',
    StateEducationAgency: 'StateEducationAgency',
    AssessmentProvider: 'AssessmentProvider',
    ServiceProvider: 'ServiceProvider'
} as const;

export type RegistrationApiRegistrationV2TenantType = typeof RegistrationApiRegistrationV2TenantType[keyof typeof RegistrationApiRegistrationV2TenantType];



