/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const TenantApiSectionsV1SectionSource = {
    Unknown: 'Unknown',
    Manual: 'Manual',
    EdFiSync: 'EdFiSync',
} as const;

export type TenantApiSectionsV1SectionSource = typeof TenantApiSectionsV1SectionSource[keyof typeof TenantApiSectionsV1SectionSource];



