/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const TenantApiPartnershipV1PartnershipSyncType = {
    Unknown: 'Unknown',
    Users: 'Users',
    Reports: 'Reports',
} as const;

export type TenantApiPartnershipV1PartnershipSyncType = typeof TenantApiPartnershipV1PartnershipSyncType[keyof typeof TenantApiPartnershipV1PartnershipSyncType];



