/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TenantApiPartnershipV1ParternshipTenantResponse } from './tenant-api-partnership-v1-parternship-tenant-response';
// May contain unused imports in some cases
// @ts-ignore
import type { TenantApiPartnershipV1PartnershipSyncDTO } from './tenant-api-partnership-v1-partnership-sync-dto';

export interface TenantApiPartnershipV1PartnershipResponse {
    'id'?: string | null;
    'partnerTenant'?: TenantApiPartnershipV1ParternshipTenantResponse;
    'partnershipType'?: string | null;
    'relatedTenants'?: Array<TenantApiPartnershipV1ParternshipTenantResponse> | null;
    'partnershipSync'?: TenantApiPartnershipV1PartnershipSyncDTO;
    'createdDateTime'?: string | null;
    'createdBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
}

