/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TenantApiPartnershipV1TenantType } from './tenant-api-partnership-v1-tenant-type';

export interface TenantApiPartnershipV1ParternshipTenantResponse {
    'tenantId'?: string | null;
    'tenantTypes'?: Array<TenantApiPartnershipV1TenantType> | null;
    'organizationIdentifier'?: string | null;
    'organizationName'?: string | null;
    'createdDateTime'?: string | null;
    'createdBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
}

