/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiContainersV1ContainerDto Types TagDto } from './validations-api-containers-v1-container-dto types tag-dto';

export interface ValidationsApiContainersV1ContainerDto {
    'tenantId'?: string | null;
    'id'?: string | null;
    'name'?: string | null;
    'description'?: string | null;
    'containerType'?: string | null;
    'parentContainerId'?: string | null;
    'isDefault'?: boolean;
    'environmentType'?: string | null;
    'childContainers'?: Array<ValidationsApiContainersV1ContainerDto> | null;
    'childContainersCount'?: number | null;
    'tags'?: Array<ValidationsApiContainersV1ContainerDto Types TagDto> | null;
    'rulesCount'?: number | null;
    'certificationStatus'?: string | null;
    'state'?: string | null;
}

