/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiJobsV1ChildJob } from './validations-api-jobs-v1-child-job';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiJobsV1JobExecutionStatus } from './validations-api-jobs-v1-job-execution-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiJobsV1JobStatus } from './validations-api-jobs-v1-job-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiJobsV1Metric } from './validations-api-jobs-v1-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiJobsV1Schedule } from './validations-api-jobs-v1-schedule';

export interface ValidationsApiJobsV1JobListResponse {
    'tenantId'?: string | null;
    'jobId'?: string | null;
    'name'?: string | null;
    'jobTypeId'?: string | null;
    'jobTypeName'?: string | null;
    'sourceConnectionId'?: string | null;
    'destinationConnectionId'?: string | null;
    'profileId'?: string | null;
    'applicationId'?: string | null;
    'schedule'?: ValidationsApiJobsV1Schedule;
    'jobStatus'?: ValidationsApiJobsV1JobStatus;
    'jobExecutionId'?: string | null;
    'jobExecutionStatus'?: ValidationsApiJobsV1JobExecutionStatus;
    'jobExecutionStartDateTime'?: string | null;
    'jobExecutionEndDateTime'?: string | null;
    'metrics'?: Array<ValidationsApiJobsV1Metric> | null;
    'childJobs'?: Array<ValidationsApiJobsV1ChildJob> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'collectionId'?: string | null;
    'jobExecutionQueuedDateTime'?: string | null;
}



