/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidationsApiReportingPeriodsV1SubmissionListResponse
 */
export interface ValidationsApiReportingPeriodsV1SubmissionListResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'createdAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'updatedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'updatedBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'tenantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'reportingPeriodId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationsApiReportingPeriodsV1SubmissionListResponse
     */
    'status'?: string | null;
}

