/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ValidationsApiCoreV1InstanceType = {
    Unknown: 'Unknown',
    Edfi: 'Edfi',
    OpenEducationAnalytics: 'OpenEducationAnalytics',
    Stadium: 'Stadium'
} as const;

export type ValidationsApiCoreV1InstanceType = typeof ValidationsApiCoreV1InstanceType[keyof typeof ValidationsApiCoreV1InstanceType];



