/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ValidationsApiContainersV1CollectionUser } from './validations-api-containers-v1-collection-user';

export interface ValidationsApiContainersV1DataUserResponse {
    'collectionId'?: string | null;
    'reportingPeriodId'?: string | null;
    'tenantId'?: string | null;
    'dataOwner'?: ValidationsApiContainersV1CollectionUser;
    'dataStewards'?: Array<ValidationsApiContainersV1CollectionUser> | null;
    'id'?: string | null;
    'environmentId'?: string | null;
}

